import { defineConfig } from "tsup"

export default defineConfig({
  entry: {
    index: "src/index.ts",
    "den/desktop-app-restrictions": "src/den/desktop-app-restrictions.ts",
    "den/desktop-policies": "src/den/desktop-policies.ts",
    "den/inference": "src/den/inference.ts",
    server: "src/server.ts",
    "server-client-method-map": "src/server-client-method-map.ts",
    "desktop-ipc": "src/desktop-ipc.ts",
    "session-archive": "src/session-archive.ts",
    browser: "src/browser.ts",
    "task-orchestrator": "src/task-orchestrator.ts",
    channel: "src/channel.ts",
    "artifact-plugin": "src/artifact-plugin.ts",
    "agent-runtime": "src/agent-runtime.ts",
    officecli: "src/officecli.ts",
    "lark-cli-auth": "src/lark-cli-auth.ts",
    "tencent-docs-connector": "src/tencent-docs-connector.ts",
    "baidu-drive-connector": "src/baidu-drive-connector.ts",
    "kdocs-connector": "src/kdocs-connector.ts",
    "dingtalk-connector": "src/dingtalk-connector.ts",
    "wecom-connector": "src/wecom-connector.ts",
    "tencent-meeting-connector": "src/tencent-meeting-connector.ts",
  },
  tsconfig: "./tsconfig.json",
  format: ["esm"],
  dts: {
    tsconfig: "./tsconfig.json",
  },
  clean: true,
  target: "es2022",
  platform: "neutral",
  sourcemap: false,
  splitting: false,
  treeshake: true,
  external: ["zod"],
})
