import { t } from "@/i18n";

import { ALL_SKILLS } from "../plugins";
import type { AgentRegistry } from "./agent-registry-types";

function localizedSkillCategoryLabel(category: string) {
  if (category === "built-in" || category === "\u5185\u7F6E\u6280\u80FD") {
    return t("agents.skill_category_builtin");
  }
  if (category === "sourcing" || category === "\u8D27\u6E90\u4E0E\u9009\u54C1") {
    return t("agents.skill_category_sourcing");
  }
  if (category === "research" || category === "\u5E02\u573A\u8C03\u7814\u4E0E\u5206\u6790") {
    return t("agents.skill_category_research");
  }
  return category;
}

function skillCategoryLabel(category: string) {
  return localizedSkillCategoryLabel(category);
}

function buildDefaultRegistry(): AgentRegistry {
  return {
  version: 1,
  updatedAt: "2026-05-29T00:00:00.000Z",
  avatars: [
    {
      id: "pixel-business",
      style: "\u50CF\u7D20\u98CE",
      label: t("agents.avatar_pixel-business_label"),
      initials: t("agents.avatar_pixel-business_initials"),
      background: "#ffd9bf",
      foreground: "#6d3b1f",
      accent: "#c14d34",
    },
    {
      id: "pixel-tech",
      style: "\u50CF\u7D20\u98CE",
      label: t("agents.avatar_pixel-tech_label"),
      initials: t("agents.avatar_pixel-tech_initials"),
      background: "#bfe5f7",
      foreground: "#16324f",
      accent: "#1f6fa5",
    },
    {
      id: "pixel-designer",
      style: "\u50CF\u7D20\u98CE",
      label: t("agents.avatar_pixel-designer_label"),
      initials: t("agents.avatar_pixel-designer_initials"),
      background: "#d6c4ff",
      foreground: "#4b2d7b",
      accent: "#9a6ce0",
    },
    {
      id: "pixel-product",
      style: "\u50CF\u7D20\u98CE",
      label: t("agents.avatar_pixel-product_label"),
      initials: t("agents.avatar_pixel-product_initials"),
      background: "#d8ddf0",
      foreground: "#4a4c63",
      accent: "#7c88b8",
    },
    {
      id: "pixel-retail",
      style: "\u50CF\u7D20\u98CE",
      label: t("agents.avatar_pixel-retail_label"),
      initials: t("agents.avatar_pixel-retail_initials"),
      background: "#c8ebb3",
      foreground: "#355a18",
      accent: "#6aa33a",
    },
    {
      id: "adventurer-guide",
      style: "\u5192\u9669\u5BB6",
      label: t("agents.avatar_adventurer-guide_label"),
      initials: t("agents.avatar_adventurer-guide_initials"),
      background: "#f7d7c6",
      foreground: "#6d311d",
      accent: "#d77f47",
    },
    {
      id: "adventurer-scout",
      style: "\u5192\u9669\u5BB6",
      label: t("agents.avatar_adventurer-scout_label"),
      initials: t("agents.avatar_adventurer-scout_initials"),
      background: "#d0f0dc",
      foreground: "#184c31",
      accent: "#4ca06d",
    },
    {
      id: "robot-analyst",
      style: "\u673A\u5668\u4EBA",
      label: t("agents.avatar_robot-analyst_label"),
      initials: t("agents.avatar_robot-analyst_initials"),
      background: "#e5e7f1",
      foreground: "#31374d",
      accent: "#7984af",
    },
    {
      id: "robot-helper",
      style: "\u673A\u5668\u4EBA",
      label: t("agents.avatar_robot-helper_label"),
      initials: t("agents.avatar_robot-helper_initials"),
      background: "#d9eefc",
      foreground: "#174767",
      accent: "#4a94d2",
    },
    {
      id: "lorelei-mentor",
      style: "\u6D1B\u857E\u83B1",
      label: t("agents.avatar_lorelei-mentor_label"),
      initials: t("agents.avatar_lorelei-mentor_initials"),
      background: "#ffd7f0",
      foreground: "#70285f",
      accent: "#d468b3",
    },
    {
      id: "lorelei-operator",
      style: "\u6D1B\u857E\u83B1",
      label: t("agents.template_shopify_assistant_name"),
      initials: t("agents.avatar_lorelei-operator_initials"),
      background: "#e4f1cf",
      foreground: "#38531c",
      accent: "#88b84a",
    },
  ],
  templates: [
    {
      id: "blank-agent",
      name: t("agents.tpl_blank-agent_name"),
      description: t("agents.tpl_blank-agent_description"),
      quote: t("agents.tpl_blank-agent_quote"),
      tone: "\u4E13\u4E1A",
      avatarStyle: "\u50CF\u7D20\u98CE",
      avatarOptionId: "pixel-tech",
      modelProvider: "\u81EA\u52A8",
      model: "Auto",
      enabledToolIds: ["filesystem", "web", "code", "utility"],
      skillIds: [],
      preferredName: "",
      preferredLanguage: "\u4E2D\u6587",
      userNote: "",
      userBackground: "",
      showInOverview: false,
      showInWizard: true,
    },
    {
      id: "daily-assistant",
      name: t("agents.tpl_daily-assistant_name"),
      description: t("agents.tpl_daily-assistant_description"),
      quote: t("agents.tpl_daily-assistant_quote"),
      tone: "\u53CB\u597D",
      avatarStyle: "\u673A\u5668\u4EBA",
      avatarOptionId: "robot-helper",
      modelProvider: "\u81EA\u52A8",
      model: "Auto",
      enabledToolIds: ["filesystem", "web", "utility", "memory"],
      skillIds: ["daily-summary", "meeting-followup"],
      preferredName: "",
      preferredLanguage: "\u4E2D\u6587",
      userNote: "",
      userBackground: "",
      showInOverview: true,
      showInWizard: true,
    },
    {
      id: "shopify-operator",
      name: t("agents.tpl_shopify-operator_name"),
      description: t("agents.tpl_shopify-operator_description"),
      quote: t("agents.tpl_shopify-operator_quote"),
      tone: "\u4E13\u5BB6",
      avatarStyle: "\u6D1B\u857E\u83B1",
      avatarOptionId: "lorelei-operator",
      modelProvider: "\u81EA\u52A8",
      model: "Auto",
      enabledToolIds: ["web", "commerce", "utility", "memory"],
      skillIds: ["product-trend-finder", "review-summary", "listing-optimizer"],
      preferredName: "",
      preferredLanguage: "\u4E2D\u6587",
      userNote: "",
      userBackground: t("agents.tpl_shopify-operator_user_background"),
      showInOverview: false,
      showInWizard: true,
    },
    {
      id: "dropshipping-helper",
      name: t("agents.tpl_dropshipping-helper_name"),
      description: t("agents.tpl_dropshipping-helper_description"),
      quote: t("agents.tpl_dropshipping-helper_quote"),
      tone: "\u4E13\u4E1A",
      avatarStyle: "\u5192\u9669\u5BB6",
      avatarOptionId: "adventurer-guide",
      modelProvider: "\u81EA\u52A8",
      model: "Auto",
      enabledToolIds: ["web", "commerce", "filesystem", "utility"],
      skillIds: ["supplier-shortlist", "listing-optimizer"],
      preferredName: "",
      preferredLanguage: "\u4E2D\u6587",
      userNote: "",
      userBackground: "",
      showInOverview: false,
      showInWizard: true,
    },
    {
      id: "engineering-helper",
      name: t("agents.tpl_engineering-helper_name"),
      description: t("agents.tpl_engineering-helper_description"),
      quote: t("agents.tpl_engineering-helper_quote"),
      tone: "\u53CB\u597D",
      avatarStyle: "\u50CF\u7D20\u98CE",
      avatarOptionId: "pixel-tech",
      modelProvider: "\u81EA\u52A8",
      model: "Auto",
      enabledToolIds: ["filesystem", "code", "web", "memory", "collaboration"],
      skillIds: ["bug-triage", "refactor-checklist", "pr-brief"],
      preferredName: "",
      preferredLanguage: "\u4E2D\u6587",
      userNote: "",
      userBackground: t("agents.tpl_engineering-helper_user_background"),
      showInOverview: false,
      showInWizard: true,
    },
    {
      id: "commerce-expert",
      name: t("agents.tpl_commerce-expert_name"),
      description: t("agents.tpl_commerce-expert_description"),
      quote: t("agents.tpl_commerce-expert_quote"),
      tone: "\u4E13\u5BB6",
      avatarStyle: "\u50CF\u7D20\u98CE",
      avatarOptionId: "pixel-retail",
      modelProvider: "\u81EA\u52A8",
      model: "Auto",
      enabledToolIds: ["web", "commerce", "utility", "memory"],
      skillIds: ["product-trend-finder", "campaign-planner", "review-summary"],
      preferredName: "",
      preferredLanguage: "\u4E2D\u6587",
      userNote: "",
      userBackground: "",
      showInOverview: false,
      showInWizard: true,
    },
    {
      id: "finance-expert",
      name: t("agents.tpl_finance-expert_name"),
      description: t("agents.tpl_finance-expert_description"),
      quote: t("agents.tpl_finance-expert_quote"),
      tone: "\u4E13\u4E1A",
      avatarStyle: "\u673A\u5668\u4EBA",
      avatarOptionId: "robot-analyst",
      modelProvider: "\u81EA\u52A8",
      model: "Auto",
      enabledToolIds: ["web", "utility", "memory", "filesystem"],
      skillIds: ["product-trend-finder", "review-summary", "campaign-planner"],
      preferredName: "",
      preferredLanguage: "\u4E2D\u6587",
      userNote: "",
      userBackground: t("agents.tpl_finance-expert_user_background"),
      showInOverview: false,
      showInWizard: true,
    },
    {
      id: "product-manager",
      name: t("agents.tpl_product-manager_name"),
      description: t("agents.tpl_product-manager_description"),
      quote: t("agents.tpl_product-manager_quote"),
      tone: "\u4E13\u4E1A",
      avatarStyle: "\u50CF\u7D20\u98CE",
      avatarOptionId: "pixel-product",
      modelProvider: "\u81EA\u52A8",
      model: "Auto",
      enabledToolIds: ["filesystem", "web", "memory", "utility"],
      skillIds: ["prd-outline", "meeting-followup", "copy-variants"],
      preferredName: "",
      preferredLanguage: "\u4E2D\u6587",
      userNote: "",
      userBackground: t("agents.tpl_product-manager_user_background"),
      showInOverview: false,
      showInWizard: true,
    },
    {
      id: "tl",
      name: t("agents.tpl_tl_name"),
      description: t("agents.tpl_tl_description"),
      quote: t("agents.tpl_tl_quote"),
      tone: "\u4E13\u4E1A",
      avatarStyle: "\u50CF\u7D20\u98CE",
      avatarOptionId: "pixel-retail",
      modelProvider: "\u81EA\u52A8",
      model: "Auto",
      enabledToolIds: ["filesystem", "web", "memory", "collaboration"],
      skillIds: ["project-radar", "meeting-followup"],
      preferredName: "",
      preferredLanguage: "\u4E2D\u6587",
      userNote: "",
      userBackground: "",
      showInOverview: false,
      showInWizard: false,
    },
    {
      id: "design-expert",
      name: t("agents.tpl_design-expert_name"),
      description: t("agents.tpl_design-expert_description"),
      quote: t("agents.tpl_design-expert_quote"),
      tone: "\u521B\u610F",
      avatarStyle: "\u50CF\u7D20\u98CE",
      avatarOptionId: "pixel-designer",
      modelProvider: "\u81EA\u52A8",
      model: "Auto",
      enabledToolIds: ["filesystem", "web", "media", "utility"],
      skillIds: ["ux-critique", "copy-variants"],
      preferredName: "",
      preferredLanguage: "\u4E2D\u6587",
      userNote: "",
      userBackground: "",
      showInOverview: false,
      showInWizard: false,
    },
    {
      id: "product-expert",
      name: t("agents.tpl_product-expert_name"),
      description: t("agents.tpl_product-expert_description"),
      quote: t("agents.tpl_product-expert_quote"),
      tone: "\u4E13\u4E1A",
      avatarStyle: "\u50CF\u7D20\u98CE",
      avatarOptionId: "pixel-product",
      modelProvider: "\u81EA\u52A8",
      model: "Auto",
      enabledToolIds: ["filesystem", "web", "memory", "utility"],
      skillIds: ["prd-outline", "meeting-followup"],
      preferredName: "",
      preferredLanguage: "\u4E2D\u6587",
      userNote: "",
      userBackground: "",
      showInOverview: false,
      showInWizard: false,
    },
    {
      id: "business-expert",
      name: t("agents.tpl_business-expert_name"),
      description: t("agents.tpl_business-expert_description"),
      quote: t("agents.tpl_business-expert_quote"),
      tone: "\u4E13\u5BB6",
      avatarStyle: "\u50CF\u7D20\u98CE",
      avatarOptionId: "pixel-business",
      modelProvider: "\u81EA\u52A8",
      model: "Auto",
      enabledToolIds: ["web", "commerce", "memory", "utility"],
      skillIds: ["product-trend-finder", "campaign-planner"],
      preferredName: "",
      preferredLanguage: "\u4E2D\u6587",
      userNote: "",
      userBackground: "",
      showInOverview: false,
      showInWizard: false,
    },
  ],
  agents: [],
  skills: ALL_SKILLS.map((skill) => ({
    id: skill.id,
    category: skillCategoryLabel(skill.category),
    group: "",
    name: skill.name,
    description: skill.description,
    enabled: skill.enabled,
  })),
};
}


export function createDefaultAgentRegistry(): AgentRegistry {
  return structuredClone(buildDefaultRegistry());
}
