/**
 * Desktop path helpers for Electron main process.
 * Extracted from main.mjs (mechanical split; main remains composition root).
 */
import { existsSync } from "node:fs";
import { mkdir } from "node:fs/promises";
import os from "node:os";
import path from "node:path";

import { resolveLocalSkillsRoot } from "./config-profile-paths.mjs";
import { ensureLocalConfigMigrated } from "./ensure-local-config-migrated.mjs";
import { ensureWorkMemoryAwareness } from "./ensure-work-memory-awareness.mjs";
import { ensureKnowledgeVault } from "./ensure-knowledge-vault.mjs";
import { resolveRealHomeDir } from "./real-home-policy.mjs";

const BUNDLED_SKILLS_RESOURCE_DIR = "bundled-skills";
const MARKETPLACE_RESOURCE_DIR = "marketplace";
/** Legacy subpath (pre profile tree); retained as dual-read fallback. */
const ONMYAGENT_USER_SKILLS_DIR_SUBPATH = ".onmyagent/skills";
const ONMYAGENT_LEGACY_USER_SKILLS_DIR_SUBPATH = "onmyagent/skills";

/**
 * Factory for desktop path helpers.
 * @param {{ dirname: string, isDevMode?: boolean }} options
 */
export function createDesktopPaths(options) {
  const electronDirname = options.dirname;
  const isDevMode = Boolean(options.isDevMode);

  let cachedBundledSkillsRootPath = undefined;
  let cachedMarketplaceRootPath = undefined;

  /**
   * Real user home (not OpenCode sandbox / Electron userData).
   * Relative ONMYAGENT_REAL_HOME still throws; a sandbox override is ignored.
   */
  function getRealHomeDir() {
    const homeOverride = process.env.ONMYAGENT_REAL_HOME?.trim();
    if (homeOverride && !path.isAbsolute(homeOverride)) {
      throw new Error("ONMYAGENT_REAL_HOME must be an absolute path");
    }
    let username = String(process.env.USER || process.env.LOGNAME || "").trim();
    if (!username) {
      try {
        username = String(os.userInfo().username || "").trim();
      } catch {
        username = "";
      }
    }
    return resolveRealHomeDir({
      override: homeOverride,
      home: [os.homedir(), process.env.HOME],
      userProfile: process.env.USERPROFILE,
      user: username,
      platform: process.platform,
    });
  }

  function claudeProjectsRoot() {
    return path.join(getRealHomeDir(), ".claude", "projects");
  }

  function bundledSkillsRootPath() {
    if (cachedBundledSkillsRootPath !== undefined) {
      return cachedBundledSkillsRootPath;
    }
    let bundledSkillsRoot = path.join(
      process.resourcesPath,
      BUNDLED_SKILLS_RESOURCE_DIR,
    );

    // Fallback for dev (`pnpm dev`): `process.resourcesPath` points to
    // `node_modules/electron/dist/...`, not our packaged resources. Look for
    // the directory generated by `electron-build.mjs` into the local repo.
    if (!existsSync(bundledSkillsRoot)) {
      const devFallback = path.resolve(
        electronDirname,
        "..",
        "resources",
        BUNDLED_SKILLS_RESOURCE_DIR,
      );
      if (existsSync(devFallback)) {
        bundledSkillsRoot = devFallback;
      }
    }

    cachedBundledSkillsRootPath = existsSync(bundledSkillsRoot)
      ? bundledSkillsRoot
      : null;
    return cachedBundledSkillsRootPath;
  }

  function marketplaceRootPath() {
    if (cachedMarketplaceRootPath !== undefined) {
      return cachedMarketplaceRootPath;
    }
    let marketplaceRoot = path.join(process.resourcesPath, MARKETPLACE_RESOURCE_DIR);
    if (!existsSync(marketplaceRoot)) {
      const devFallback = path.resolve(electronDirname, "..", "resources", MARKETPLACE_RESOURCE_DIR);
      if (existsSync(devFallback)) {
        marketplaceRoot = devFallback;
      }
    }
    cachedMarketplaceRootPath = existsSync(marketplaceRoot) ? marketplaceRoot : null;
    return cachedMarketplaceRootPath;
  }

  async function ensureOnMyAgentUserDataDirs() {
    const home = getRealHomeDir();
    await mkdir(path.join(home, ".onmyagent", "agents"), {
      recursive: true,
    });
    // Stage-2: copy skills/experts into profiles/local/config (never deletes legacy).
    // Soft-fail: dual-read still serves legacy roots if migration fails.
    try {
      const migrated = await ensureLocalConfigMigrated({ homeDir: home });
      if (!migrated.ok) {
        console.warn(
          "[config-profile] local migrate failed; using dual-read legacy",
          migrated.error,
        );
      }
    } catch (error) {
      console.warn("[config-profile] local migrate threw", error);
    }
    // Ensure active skills root exists (profile after complete, else legacy).
    await mkdir(onmyagentUserSkillsRoot(), { recursive: true });
    // Install / first cold-start: seed style.md, AGENTS.md, USER.md, MEMORY.md
    // under data/user/awareness/main (idempotent; never overwrites).
    try {
      await ensureWorkMemoryAwareness({ homeDir: home });
    } catch (error) {
      console.warn("[work-memory] ensure awareness seeds failed", error);
    }
    try {
      await ensureKnowledgeVault({ homeDir: home });
    } catch (error) {
      console.warn("[knowledge] ensure vault seed failed", error);
    }
  }

  function desktopBootstrapPath() {
    if (process.env.ONMYAGENT_DESKTOP_BOOTSTRAP_PATH?.trim()) {
      return process.env.ONMYAGENT_DESKTOP_BOOTSTRAP_PATH.trim();
    }
    return path.join(
      os.homedir(),
      ".config",
      "onmyagent",
      "desktop-bootstrap.json",
    );
  }

  function workspaceStatePath(userDataPath) {
    return path.join(userDataPath, "onmyagent-workspaces.json");
  }

  function userAgentRegistryPath() {
    return path.join(getRealHomeDir(), ".onmyagent", "agents", "registry.json");
  }

  function onmyagentUserSkillsRoot() {
    // Dual-read / post-migrate profile path (see config-profile-paths).
    return resolveLocalSkillsRoot(getRealHomeDir());
  }

  function legacyOnmyagentUserSkillsRoot() {
    return path.join(getRealHomeDir(), ONMYAGENT_LEGACY_USER_SKILLS_DIR_SUBPATH);
  }

  function legacyElectronWorkspaceStatePath(userDataPath) {
    return path.join(userDataPath, "workspace-state.json");
  }

  function configHomePath() {
    if (process.env.XDG_CONFIG_HOME?.trim()) {
      return process.env.XDG_CONFIG_HOME.trim();
    }
    if (process.platform === "win32" && process.env.APPDATA?.trim()) {
      return process.env.APPDATA.trim();
    }
    return path.join(os.homedir(), ".config");
  }

  function globalOpencodeRoot() {
    return path.join(configHomePath(), "opencode");
  }

  function resolveAppIconPath() {
    const candidates = [
      // Dev: match Tauri's separate dev icon so the dev app is visibly distinct.
      ...(isDevMode
        ? [
            path.resolve(electronDirname, "../resources/icons/dev/icon.png"),
            path.resolve(electronDirname, "../resources/icons/dev/128x128@2x.png"),
            path.resolve(electronDirname, "../resources/icons/dev/icon-dev.icns"),
          ]
        : []),
      // Repo-relative path to the Electron resource icon set.
      path.resolve(electronDirname, "../resources/icons/icon.png"),
      // Packaged: electron-builder copies extraResources but we fall back to this
      // if custom packaging ever exposes the icon here.
      path.join(process.resourcesPath ?? "", "icons", "icon.png"),
    ];
    for (const candidate of candidates) {
      if (candidate && existsSync(candidate)) return candidate;
    }
    return null;
  }

  function isBundledSkillPath(targetPath) {
    const bundledRoot = bundledSkillsRootPath();
    if (!bundledRoot) return false;
    const relativePath = path.relative(bundledRoot, targetPath);
    return Boolean(relativePath) && !relativePath.startsWith("..") && !path.isAbsolute(relativePath);
  }

  return {
    ONMYAGENT_USER_SKILLS_DIR_SUBPATH,
    ONMYAGENT_LEGACY_USER_SKILLS_DIR_SUBPATH,
    BUNDLED_SKILLS_RESOURCE_DIR,
    MARKETPLACE_RESOURCE_DIR,
    getRealHomeDir,
    claudeProjectsRoot,
    bundledSkillsRootPath,
    marketplaceRootPath,
    ensureOnMyAgentUserDataDirs,
    desktopBootstrapPath,
    workspaceStatePath,
    userAgentRegistryPath,
    onmyagentUserSkillsRoot,
    legacyOnmyagentUserSkillsRoot,
    legacyElectronWorkspaceStatePath,
    configHomePath,
    globalOpencodeRoot,
    resolveAppIconPath,
    isBundledSkillPath,
  };
}
