/**
 * Desktop path helpers for Electron main process.
 * Extracted from main.mjs (mechanical split; main remains composition root).
 */
import { existsSync } from "node:fs";
import { mkdir } from "node:fs/promises";
import os from "node:os";
import path from "node:path";

const BUNDLED_SKILLS_RESOURCE_DIR = "bundled-skills";
const MARKETPLACE_RESOURCE_DIR = "marketplace";
const ONMYAGENT_USER_SKILLS_DIR_SUBPATH = ".onmyagent/skills";
const ONMYAGENT_LEGACY_USER_SKILLS_DIR_SUBPATH = "onmyagent/skills";

/**
 * Factory for desktop path helpers.
 * @param {{ dirname: string, isDevMode?: boolean }} options
 */
export function createDesktopPaths(options) {
  const electronDirname = options.dirname;
  const isDevMode = Boolean(options.isDevMode);

  let cachedBundledSkillsRootPath = undefined;
  let cachedMarketplaceRootPath = undefined;

  /**
   * 获取真实家目录路径（不受 Electron dev 沙箱影响）
   *
   * 重要：Electron dev 模式（runtime.mjs #ensureDevModePaths）会把
   * process.env.HOME / XDG_CONFIG_HOME 等重定向到沙箱目录
   *  (~/Library/Application Support/com.differentai.onmyagent.dev/onmyagent-dev-data/home)
   * 这导致 os.homedir() 和 process.env.HOME 都返回沙箱路径。
   *
   * 因此我们用 platform 和 process.env.USER 直接构造真实家目录路径。
   */
  function getRealHomeDir() {
    const user = process.env.USER || os.userInfo().username;
    if (user) {
      if (process.platform === "darwin") {
        return path.join("/Users", user);
      }
      if (process.platform === "linux") {
        // 先尝试 os.homedir()（如果不是沙箱路径），否则用 /home 兜底
        const home = os.homedir();
        if (home && !home.includes("Library/Application Support")) {
          return home;
        }
        return path.join("/home", user);
      }
      if (process.platform === "win32") {
        return process.env.USERPROFILE || path.join("C:", "Users", user);
      }
    }
    return os.homedir();
  }

  function claudeProjectsRoot() {
    return path.join(getRealHomeDir(), ".claude", "projects");
  }

  function bundledSkillsRootPath() {
    if (cachedBundledSkillsRootPath !== undefined) {
      return cachedBundledSkillsRootPath;
    }
    let bundledSkillsRoot = path.join(
      process.resourcesPath,
      BUNDLED_SKILLS_RESOURCE_DIR,
    );

    // Fallback for dev (`pnpm dev`): `process.resourcesPath` points to
    // `node_modules/electron/dist/...`, not our packaged resources. Look for
    // the directory generated by `electron-build.mjs` into the local repo.
    if (!existsSync(bundledSkillsRoot)) {
      const devFallback = path.resolve(
        electronDirname,
        "..",
        "resources",
        BUNDLED_SKILLS_RESOURCE_DIR,
      );
      if (existsSync(devFallback)) {
        bundledSkillsRoot = devFallback;
      }
    }

    cachedBundledSkillsRootPath = existsSync(bundledSkillsRoot)
      ? bundledSkillsRoot
      : null;
    return cachedBundledSkillsRootPath;
  }

  function marketplaceRootPath() {
    if (cachedMarketplaceRootPath !== undefined) {
      return cachedMarketplaceRootPath;
    }
    let marketplaceRoot = path.join(process.resourcesPath, MARKETPLACE_RESOURCE_DIR);
    if (!existsSync(marketplaceRoot)) {
      const devFallback = path.resolve(electronDirname, "..", "resources", MARKETPLACE_RESOURCE_DIR);
      if (existsSync(devFallback)) {
        marketplaceRoot = devFallback;
      }
    }
    cachedMarketplaceRootPath = existsSync(marketplaceRoot) ? marketplaceRoot : null;
    return cachedMarketplaceRootPath;
  }

  async function ensureOnMyAgentUserDataDirs() {
    await mkdir(path.join(getRealHomeDir(), ".onmyagent", "agents"), {
      recursive: true,
    });
    await mkdir(path.join(getRealHomeDir(), ONMYAGENT_USER_SKILLS_DIR_SUBPATH), {
      recursive: true,
    });
  }

  function desktopBootstrapPath() {
    if (process.env.ONMYAGENT_DESKTOP_BOOTSTRAP_PATH?.trim()) {
      return process.env.ONMYAGENT_DESKTOP_BOOTSTRAP_PATH.trim();
    }
    return path.join(
      os.homedir(),
      ".config",
      "onmyagent",
      "desktop-bootstrap.json",
    );
  }

  function workspaceStatePath(userDataPath) {
    return path.join(userDataPath, "onmyagent-workspaces.json");
  }

  function userAgentRegistryPath() {
    return path.join(getRealHomeDir(), ".onmyagent", "agents", "registry.json");
  }

  function onmyagentUserSkillsRoot() {
    return path.join(getRealHomeDir(), ONMYAGENT_USER_SKILLS_DIR_SUBPATH);
  }

  function legacyOnmyagentUserSkillsRoot() {
    return path.join(getRealHomeDir(), ONMYAGENT_LEGACY_USER_SKILLS_DIR_SUBPATH);
  }

  function legacyElectronWorkspaceStatePath(userDataPath) {
    return path.join(userDataPath, "workspace-state.json");
  }

  function configHomePath() {
    if (process.env.XDG_CONFIG_HOME?.trim()) {
      return process.env.XDG_CONFIG_HOME.trim();
    }
    if (process.platform === "win32" && process.env.APPDATA?.trim()) {
      return process.env.APPDATA.trim();
    }
    return path.join(os.homedir(), ".config");
  }

  function globalOpencodeRoot() {
    return path.join(configHomePath(), "opencode");
  }

  function resolveAppIconPath() {
    const candidates = [
      // Dev: match Tauri's separate dev icon so the dev app is visibly distinct.
      ...(isDevMode
        ? [
            path.resolve(electronDirname, "../resources/icons/dev/icon.png"),
            path.resolve(electronDirname, "../resources/icons/dev/128x128@2x.png"),
            path.resolve(electronDirname, "../resources/icons/dev/icon-dev.icns"),
          ]
        : []),
      // Repo-relative path to the Electron resource icon set.
      path.resolve(electronDirname, "../resources/icons/icon.png"),
      // Packaged: electron-builder copies extraResources but we fall back to this
      // if custom packaging ever exposes the icon here.
      path.join(process.resourcesPath ?? "", "icons", "icon.png"),
    ];
    for (const candidate of candidates) {
      if (candidate && existsSync(candidate)) return candidate;
    }
    return null;
  }

  function isBundledSkillPath(targetPath) {
    const bundledRoot = bundledSkillsRootPath();
    if (!bundledRoot) return false;
    const relativePath = path.relative(bundledRoot, targetPath);
    return Boolean(relativePath) && !relativePath.startsWith("..") && !path.isAbsolute(relativePath);
  }

  return {
    ONMYAGENT_USER_SKILLS_DIR_SUBPATH,
    ONMYAGENT_LEGACY_USER_SKILLS_DIR_SUBPATH,
    BUNDLED_SKILLS_RESOURCE_DIR,
    MARKETPLACE_RESOURCE_DIR,
    getRealHomeDir,
    claudeProjectsRoot,
    bundledSkillsRootPath,
    marketplaceRootPath,
    ensureOnMyAgentUserDataDirs,
    desktopBootstrapPath,
    workspaceStatePath,
    userAgentRegistryPath,
    onmyagentUserSkillsRoot,
    legacyOnmyagentUserSkillsRoot,
    legacyElectronWorkspaceStatePath,
    configHomePath,
    globalOpencodeRoot,
    resolveAppIconPath,
    isBundledSkillPath,
  };
}
