import { readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

// Background auto-update for packaged desktop builds.
//
// Primary path (packaged macOS / Windows): electron-updater drives the whole
// flow — it reads app-update.yml (generated by electron-builder from the
// GitHub provider config), checks for updates honoring prereleases, downloads
// the new package + blockmaps in the background, and surfaces progress via the
// IPC channels below. Nothing installs until the user clicks "Restart and
// install" (autoInstallOnAppQuit is false by design).
//
// Fallback path (Linux, dev, or when electron-updater fails to initialize):
// the hand-written GitHub Releases API checker detects a newer version and
// opens the release page in the default browser. The list endpoint (not
// /latest) is used so prereleases are visible.
//
// Prerelease note: all current OnMyAgent releases are prereleases. GitHub's
// /releases/latest ignores them, so allowPrerelease=true (electron-updater)
// and the /releases list endpoint (fallback) are both required for updates to
// be detected at all.

const DEFAULT_RELEASES_LIST_API =
  "https://api.github.com/repos/WeaveQ/OnMyAgent/releases?per_page=5";
const RELEASES_HTML_URL =
  "https://github.com/WeaveQ/OnMyAgent/releases/latest";
/** Same cadence for packaged + unpackaged (dev) builds. */
const CHECK_INTERVAL_MS = 6 * 60 * 60 * 1000; // 6h
const INITIAL_CHECK_DELAY_MS = 30 * 1000; // ~30s after app ready
/** Slightly generous: api.github.com is often slow or filtered. */
const FETCH_TIMEOUT_MS = 15 * 1000;
const FETCH_RETRY_COUNT = 1;
const FETCH_RETRY_DELAY_MS = 1_200;
/**
 * Unpackaged (dev) background polling is ON by default — same 30s / 6h as
 * packaged. Opt out with ONMYAGENT_UPDATE_CHECK_IN_DEV=0|false|off.
 */
const UPDATE_CHECK_IN_DEV_ENV = String(
  process.env.ONMYAGENT_UPDATE_CHECK_IN_DEV ?? "",
)
  .trim()
  .toLowerCase();
const UPDATE_CHECK_IN_DEV_DISABLED =
  UPDATE_CHECK_IN_DEV_ENV === "0" ||
  UPDATE_CHECK_IN_DEV_ENV === "false" ||
  UPDATE_CHECK_IN_DEV_ENV === "off";
/** Optional mirror / override for the releases list JSON endpoint. */
const RELEASES_LIST_API_OVERRIDE = String(
  process.env.ONMYAGENT_UPDATE_API ?? "",
).trim();

const __updater_dirname = path.dirname(fileURLToPath(import.meta.url));
let _cachedAppVersion = null;

function resolveAppVersion(app) {
  if (_cachedAppVersion) return _cachedAppVersion;
  const electronVersion = app.getVersion();
  if (app.isPackaged) {
    _cachedAppVersion = electronVersion;
    return electronVersion;
  }
  try {
    const pkgPath = path.resolve(__updater_dirname, "..", "package.json");
    const pkg = JSON.parse(readFileSync(pkgPath, "utf8"));
    _cachedAppVersion = pkg.version || electronVersion;
  } catch {
    _cachedAppVersion = electronVersion;
  }
  return _cachedAppVersion;
}

function parseComparableVersion(value) {
  if (typeof value !== "string") return null;
  const normalized = value.trim().replace(/^v/i, "");
  if (!normalized) return null;
  const [versionCore] = normalized.split("+", 1);
  if (!versionCore) return null;
  const [releasePart, prereleasePart = ""] = versionCore.split("-", 2);
  const release = releasePart.split(".").map((segment) => Number(segment));
  if (!release.length || release.some((segment) => !Number.isInteger(segment) || segment < 0)) {
    return null;
  }
  const prerelease = prereleasePart
    .split(".")
    .map((segment) => segment.trim())
    .filter(Boolean);
  return { release, prerelease };
}

function comparePrereleaseIdentifiers(left, right) {
  if (!left.length && !right.length) return 0;
  if (!left.length) return 1;
  if (!right.length) return -1;
  const count = Math.max(left.length, right.length);
  for (let index = 0; index < count; index += 1) {
    const leftPart = left[index];
    const rightPart = right[index];
    if (leftPart === undefined) return -1;
    if (rightPart === undefined) return 1;
    const leftNumeric = /^\d+$/.test(leftPart) ? Number(leftPart) : null;
    const rightNumeric = /^\d+$/.test(rightPart) ? Number(rightPart) : null;
    if (leftNumeric !== null && rightNumeric !== null) {
      if (leftNumeric !== rightNumeric) return leftNumeric < rightNumeric ? -1 : 1;
      continue;
    }
    if (leftNumeric !== null) return -1;
    if (rightNumeric !== null) return 1;
    const comparison = leftPart.localeCompare(rightPart);
    if (comparison !== 0) return comparison < 0 ? -1 : 1;
  }
  return 0;
}

function compareVersions(left, right) {
  const parsedLeft = parseComparableVersion(left);
  const parsedRight = parseComparableVersion(right);
  if (!parsedLeft || !parsedRight) return null;
  const count = Math.max(parsedLeft.release.length, parsedRight.release.length);
  for (let index = 0; index < count; index += 1) {
    const leftPart = parsedLeft.release[index] ?? 0;
    const rightPart = parsedRight.release[index] ?? 0;
    if (leftPart !== rightPart) return leftPart < rightPart ? -1 : 1;
  }
  return comparePrereleaseIdentifiers(parsedLeft.prerelease, parsedRight.prerelease);
}

function isVersionNewer(candidate, current) {
  const comparison = compareVersions(candidate, current);
  return comparison === null ? candidate !== current : comparison > 0;
}

export {
  compareVersions,
  isVersionNewer,
  parseComparableVersion,
};

function channelState(app, platformFlow) {
  return {
    channel: "stable",
    feedUrl: RELEASES_HTML_URL,
    currentVersion: resolveAppVersion(app),
    /** Lightweight / electron-updater feed has no alpha channel. */
    alphaSupported: false,
    /** "in-app" = download + restart-to-install; "open-browser" = fallback. */
    platformFlow,
  };
}

/**
 * Classify fetch failures so the renderer can soft-fail with i18n.
 * @returns {{ code: "timeout" | "network" | "http" | "unknown", message: string, soft: boolean }}
 */
function classifyFetchError(error) {
  const name = error && typeof error === "object" ? error.name : null;
  const message = String(error?.message ?? error ?? "");
  if (
    name === "AbortError" ||
    name === "TimeoutError" ||
    /aborted|timeout/i.test(message)
  ) {
    return {
      code: "timeout",
      message:
        "Network timed out while contacting the update server. You can open the release page in a browser instead.",
      soft: true,
    };
  }
  if (
    /fetch failed|ECONN|ENOTFOUND|EAI_AGAIN|network|socket|CERT|SSL|TLS/i.test(
      message,
    )
  ) {
    return {
      code: "network",
      message:
        "Could not reach the update server. Check your network or proxy, or open the release page in a browser.",
      soft: true,
    };
  }
  if (/GitHub API responded/i.test(message)) {
    return { code: "http", message, soft: true };
  }
  return {
    code: "unknown",
    message: message || "Failed to check for updates.",
    soft: true,
  };
}

function sleep(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

function normalizeReleaseEntry(data) {
  if (!data || typeof data !== "object") return null;
  const tagName = typeof data.tag_name === "string" ? data.tag_name : null;
  if (!tagName) return null;
  return {
    tagName,
    htmlUrl:
      typeof data.html_url === "string" ? data.html_url : RELEASES_HTML_URL,
    name: typeof data.name === "string" ? data.name : null,
    publishedAt:
      typeof data.published_at === "string" ? data.published_at : null,
    body: typeof data.body === "string" ? data.body : null,
    prerelease: data.prerelease === true,
    draft: data.draft === true,
  };
}

/**
 * Fetch the newest non-draft release from the GitHub list endpoint. Prereleases
 * are included because /releases/latest ignores them and all current releases
 * are prereleases. The list is already newest-first; we pick the first entry
 * that is newer than the running version (so a stable patch above a prerelease
 * is reachable too).
 */
/**
 * @param {{ currentVersion?: string }} [options]
 */
async function fetchLatestReleaseOnce(options = {}) {
  const { currentVersion } = options;
  const apiUrl = RELEASES_LIST_API_OVERRIDE || DEFAULT_RELEASES_LIST_API;
  const controller = new AbortController();
  const timer = setTimeout(
    () => controller.abort(new Error("timeout")),
    FETCH_TIMEOUT_MS,
  );
  try {
    const response = await fetch(apiUrl, {
      headers: {
        Accept: "application/vnd.github+json",
        "User-Agent": "OnMyAgent-UpdateChecker",
      },
      signal: controller.signal,
    });
    if (response.status === 404) {
      return { notPublished: true };
    }
    if (!response.ok) {
      throw new Error(`GitHub API responded ${response.status}`);
    }
    const data = await response.json();
    if (!Array.isArray(data) || data.length === 0) {
      return { notPublished: true };
    }
    const releases = data
      .map(normalizeReleaseEntry)
      .filter((entry) => entry && !entry.draft);
    if (releases.length === 0) {
      return { notPublished: true };
    }
    if (!currentVersion) return releases[0];
    // First entry newer than current; fall back to the newest entry if none is
    // (caller decides availability via isVersionNewer anyway).
    const newer = releases.find((entry) =>
      isVersionNewer(entry.tagName, currentVersion),
    );
    return newer ?? releases[0];
  } finally {
    clearTimeout(timer);
  }
}

/** One retry on soft network/timeout failures. */
async function fetchLatestRelease(options) {
  let lastError = null;
  for (let attempt = 0; attempt <= FETCH_RETRY_COUNT; attempt += 1) {
    try {
      return await fetchLatestReleaseOnce(options);
    } catch (error) {
      lastError = error;
      const classified = classifyFetchError(error);
      if (!classified.soft || attempt >= FETCH_RETRY_COUNT) break;
      await sleep(FETCH_RETRY_DELAY_MS);
    }
  }
  throw lastError;
}

/**
 * Decide whether electron-updater should drive updates. Packaged macOS and
 * Windows builds use it; Linux and unpackaged (dev) builds use the fallback.
 */
function supportsInAppUpdater(app, platform) {
  if (!app.isPackaged) return false;
  return platform === "darwin" || platform === "win32";
}

/**
 * @param {{
 *   app: import("electron").App,
 *   ipcMain: import("electron").IpcMain,
 *   getMainWindow: () => import("electron").BrowserWindow | null | undefined,
 *   Notification?: typeof import("electron").Notification,
 *   shell?: import("electron").Shell,
 *   platform?: NodeJS.Platform,
 * }} options
 */
export function registerUpdaterIpc({
  app,
  ipcMain,
  getMainWindow,
  Notification,
  shell,
  platform = process.platform,
}) {
  const inAppSupported = supportsInAppUpdater(app, platform);
  const platformFlow = inAppSupported ? "in-app" : "open-browser";
  /** True only on macOS in-app path, where unnotarized builds hit Gatekeeper. */
  const macQuarantineNotice = inAppSupported && platform === "darwin";

  let lastNotifiedVersion = null;
  /** @type {Record<string, unknown> | null} */
  let lastKnownAvailable = null;
  /** @type {import("electron-updater").AppUpdater | null} */
  let autoUpdater = null;
  let updaterInitError = null;
  /** Tracks the download state emitted by electron-updater. */
  let downloadState = { active: false, percent: 0, ready: false, info: null };
  /** Set when update-downloaded fires so installAndRestart can act. */
  let downloadedUpdateInfo = null;

  function sendToRenderer(channel, payload) {
    try {
      const win = typeof getMainWindow === "function" ? getMainWindow() : null;
      if (win?.webContents && !win.isDestroyed()) {
        win.webContents.send(channel, payload);
      }
    } catch {
      // Renderer may be gone; ignore.
    }
  }

  function emitAvailable(payload) {
    sendToRenderer("onmyagent:updater:available", payload);
  }

  function emitDownloadProgress(payload) {
    sendToRenderer("onmyagent:updater:download-progress", payload);
  }

  function openReleasePage(url) {
    const target = url || RELEASES_HTML_URL;
    if (shell?.openExternal) {
      shell.openExternal(target).catch(() => undefined);
    }
  }

  /**
   * Common envelope for availability payloads so the renderer gets the same
   * shape regardless of which path produced it.
   */
  function buildAvailabilityPayload(partial) {
    return {
      platformFlow,
      macQuarantineNotice,
      readyToInstall: downloadState.ready,
      ...partial,
    };
  }

  function persistLastKnown(payload) {
    lastKnownAvailable = payload;
    return payload;
  }

  // -- electron-updater initialization (packaged macOS / Windows only) -------

  async function initAutoUpdater() {
    if (autoUpdater || updaterInitError) return autoUpdater;
    if (!inAppSupported) return null;
    try {
      const mod = await import("electron-updater");
      autoUpdater = mod.autoUpdater ?? mod.default?.autoUpdater ?? null;
      if (!autoUpdater) {
        throw new Error("electron-updater did not expose an autoUpdater instance.");
      }
      // All current releases are prereleases; without this, nothing is found.
      autoUpdater.allowPrerelease = true;
      // We download proactively in the background but never install on quit.
      autoUpdater.autoDownload = true;
      autoUpdater.autoInstallOnAppQuit = false;
      autoUpdater.autoRunAppAfterInstall = true;

      autoUpdater.on("checking-for-update", () => {
        // No payload; renderer already shows its own checking state for
        // manual checks. Background poller is silent until a result.
      });

      autoUpdater.on("update-available", /** @param {any} info */ (info) => {
        const latestVersion =
          typeof info?.version === "string"
            ? info.version
            : String(info?.version ?? "").replace(/^v/i, "");
        const releaseNotes =
          typeof info?.releaseNotes === "string"
            ? info.releaseNotes
            : Array.isArray(info?.releaseNotes)
              ? info.releaseNotes
              : null;
        const payload = buildAvailabilityPayload({
          available: true,
          currentVersion: resolveAppVersion(app),
          latestVersion: latestVersion || null,
          releaseTag: info?.releaseName ? String(info.releaseName) : latestVersion ? `v${latestVersion}` : null,
          releaseUrl: RELEASES_HTML_URL,
          releaseName: typeof info?.releaseName === "string" ? info.releaseName : null,
          releaseDate:
            typeof info?.releaseDate === "string"
              ? info.releaseDate
              : info?.releaseDate instanceof Date
                ? info.releaseDate.toISOString()
                : null,
          releaseNotes,
        });
        persistLastKnown(payload);
        emitAvailable(payload);
        maybeNotify(latestVersion, payload);
        // autoDownload=true kicks off the download immediately; signal it.
        downloadState = {
          active: true,
          percent: 0,
          ready: false,
          info,
        };
        emitDownloadProgress({
          platformFlow,
          state: "downloading",
          percent: 0,
          transferred: 0,
          total: 0,
          bytesPerSecond: 0,
        });
      });

      autoUpdater.on("download-progress", /** @param {any} progress */ (progress) => {
        const percent =
          typeof progress?.percent === "number" ? progress.percent : 0;
        downloadState = {
          ...downloadState,
          active: percent < 100,
          percent,
        };
        emitDownloadProgress({
          platformFlow,
          state: "downloading",
          percent,
          transferred:
            typeof progress?.transferred === "number" ? progress.transferred : 0,
          total: typeof progress?.total === "number" ? progress.total : 0,
          bytesPerSecond:
            typeof progress?.bytesPerSecond === "number"
              ? progress.bytesPerSecond
              : 0,
        });
      });

      autoUpdater.on("update-downloaded", /** @param {any} info */ (info) => {
        downloadedUpdateInfo = info ?? null;
        downloadState = { active: false, percent: 100, ready: true, info };
        const latestVersion =
          typeof info?.version === "string"
            ? info.version
            : String(info?.version ?? "").replace(/^v/i, "");
        const readyPayload = buildAvailabilityPayload({
          available: true,
          currentVersion: resolveAppVersion(app),
          latestVersion: latestVersion || lastKnownAvailable?.latestVersion || null,
          releaseTag: info?.releaseName ? String(info.releaseName) : latestVersion ? `v${latestVersion}` : null,
          releaseUrl: RELEASES_HTML_URL,
          releaseName: typeof info?.releaseName === "string" ? info.releaseName : null,
          releaseDate:
            typeof info?.releaseDate === "string"
              ? info.releaseDate
              : info?.releaseDate instanceof Date
                ? info.releaseDate.toISOString()
                : null,
          releaseNotes:
            typeof info?.releaseNotes === "string"
              ? info.releaseNotes
              : Array.isArray(info?.releaseNotes)
                ? info.releaseNotes
                : null,
          readyToInstall: true,
        });
        persistLastKnown(readyPayload);
        emitAvailable(readyPayload);
        emitDownloadProgress({
          platformFlow,
          state: "ready",
          percent: 100,
          readyToInstall: true,
        });
        maybeNotify(latestVersion, readyPayload, true);
      });

      autoUpdater.on("update-not-available", /** @param {any} info */ (info) => {
        downloadState = { active: false, percent: 0, ready: false, info: null };
        const payload = buildAvailabilityPayload({
          available: false,
          currentVersion: resolveAppVersion(app),
          latestVersion:
            typeof info?.version === "string" ? info.version : null,
          reason: "You're up to date.",
          reasonCode: "up_to_date",
          soft: true,
          releaseUrl: RELEASES_HTML_URL,
        });
        persistLastKnown(payload);
      });

      autoUpdater.on("error", /** @param {Error} error */ (error) => {
        downloadState = { ...downloadState, active: false };
        const classified = classifyFetchError(error);
        const payload = buildAvailabilityPayload({
          available: false,
          currentVersion: resolveAppVersion(app),
          reason: classified.message,
          reasonCode: classified.code,
          soft: classified.soft,
          releaseUrl: RELEASES_HTML_URL,
        });
        // Keep a previous successful availability result for UI badges.
        if (!lastKnownAvailable?.latestVersion) {
          persistLastKnown(payload);
        }
        emitDownloadProgress({
          platformFlow,
          state: "error",
          error: classified.message,
        });
      });

      return autoUpdater;
    } catch (error) {
      updaterInitError = error;
      autoUpdater = null;
      return null;
    }
  }

  function maybeNotify(version, payload, isReady = false) {
    if (!version) return;
    if (lastNotifiedVersion === version && !isReady) return;
    lastNotifiedVersion = version;
    try {
      if (Notification?.isSupported?.()) {
        const notification = new Notification({
          title: isReady ? "OnMyAgent update ready" : "OnMyAgent update available",
          body: isReady
            ? `Version ${version} is downloaded. Restart to install.`
            : `Version ${version} is available. Downloading in the background.`,
          silent: false,
        });
        notification.on("click", () => {
          if (isReady) {
            // Focus the window so the user can click "Restart and install".
            const win = getMainWindow?.();
            if (win && !win.isDestroyed()) {
              if (win.isMinimized()) win.restore();
              win.show();
              win.focus();
            }
          } else {
            openReleasePage(payload?.releaseUrl);
          }
        });
        notification.show();
      }
    } catch {
      // Notifications may fail on headless CI; ignore.
    }
  }

  // -- Fallback GitHub API checker (Linux / dev / init failure) --------------

  /**
   * @param {{ silent: boolean }} options
   *   silent: when true, skip OS notification (manual Settings check).
   */
  async function performFallbackCheck({ silent }) {
    const currentVersion = resolveAppVersion(app);
    try {
      const release = await fetchLatestRelease({ currentVersion });
      if (release?.notPublished) {
        return persistLastKnown(
          buildAvailabilityPayload({
            available: false,
            currentVersion,
            reason: "No releases have been published yet.",
            reasonCode: "not_published",
            soft: true,
            releaseUrl: RELEASES_HTML_URL,
          }),
        );
      }
      if (!release?.tagName) {
        return persistLastKnown(
          buildAvailabilityPayload({
            available: false,
            reason: "No release found.",
            reasonCode: "not_published",
            soft: true,
            currentVersion,
            releaseUrl: RELEASES_HTML_URL,
          }),
        );
      }
      const available = isVersionNewer(release.tagName, currentVersion);
      const payload = persistLastKnown(
        buildAvailabilityPayload({
          available,
          currentVersion,
          latestVersion: release.tagName.replace(/^v/i, ""),
          releaseTag: release.tagName,
          releaseUrl: release.htmlUrl,
          releaseName: release.name,
          releaseDate: release.publishedAt,
          releaseNotes: release.body,
        }),
      );
      if (available) {
        emitAvailable(payload);
        if (!silent && lastNotifiedVersion !== release.tagName) {
          lastNotifiedVersion = release.tagName;
          try {
            if (Notification?.isSupported?.()) {
              const notification = new Notification({
                title: "OnMyAgent update available",
                body: `Version ${payload.latestVersion} is available. Click to open the release page.`,
                silent: false,
              });
              notification.on("click", () => openReleasePage(release.htmlUrl));
              notification.show();
            }
          } catch {
            // ignore
          }
        }
      }
      return payload;
    } catch (error) {
      const classified = classifyFetchError(error);
      const payload = buildAvailabilityPayload({
        available: false,
        currentVersion,
        reason: classified.message,
        reasonCode: classified.code,
        soft: classified.soft,
        releaseUrl: RELEASES_HTML_URL,
      });
      if (!lastKnownAvailable?.latestVersion) {
        persistLastKnown(payload);
      }
      return payload;
    }
  }

  async function performCheck(options) {
    if (autoUpdater) {
      try {
        await autoUpdater.checkForUpdates();
        return (
          lastKnownAvailable ??
          buildAvailabilityPayload({
            available: false,
            currentVersion: resolveAppVersion(app),
          })
        );
      } catch (error) {
        // If electron-updater's check throws, fall through to the API checker.
        const classified = classifyFetchError(error);
        const payload = buildAvailabilityPayload({
          available: false,
          currentVersion: resolveAppVersion(app),
          reason: classified.message,
          reasonCode: classified.code,
          soft: classified.soft,
          releaseUrl: RELEASES_HTML_URL,
        });
        if (!lastKnownAvailable?.latestVersion) persistLastKnown(payload);
        return payload;
      }
    }
    return performFallbackCheck(options);
  }

  // -- IPC handlers ----------------------------------------------------------

  ipcMain.handle("onmyagent:updater:getChannel", async () =>
    channelState(app, platformFlow),
  );

  ipcMain.handle(
    "onmyagent:updater:setChannel",
    async (_event, rawChannel) => {
      const state = channelState(app, platformFlow);
      const requested =
        rawChannel === "alpha" || rawChannel === "stable"
          ? rawChannel
          : "stable";
      return {
        ...state,
        requestedChannel: requested,
        reason:
          requested === "alpha"
            ? "Alpha channel is not supported by the updater."
            : undefined,
      };
    },
  );

  ipcMain.handle("onmyagent:updater:check", async () => {
    const result = await performCheck({ silent: true });
    return {
      ...result,
      channel: "stable",
      feedUrl: RELEASES_HTML_URL,
    };
  });

  ipcMain.handle("onmyagent:updater:getLastKnown", async () => {
    if (lastKnownAvailable) return lastKnownAvailable;
    return buildAvailabilityPayload({
      available: false,
      currentVersion: resolveAppVersion(app),
    });
  });

  // In-app path: start (or resume) the electron-updater download.
  // Fallback path: open the GitHub release page in the browser.
  ipcMain.handle("onmyagent:updater:download", async () => {
    if (downloadState.ready) {
      return { ok: true, readyToInstall: true, platformFlow };
    }
    if (autoUpdater) {
      try {
        if (!downloadState.active) {
          downloadState = { ...downloadState, active: true, percent: 0 };
          emitDownloadProgress({
            platformFlow,
            state: "downloading",
            percent: 0,
          });
          // fire-and-forget; events drive progress/ready state
          void autoUpdater.downloadUpdate().catch((error) => {
            downloadState = { ...downloadState, active: false };
            emitDownloadProgress({
              platformFlow,
              state: "error",
              error: classifyFetchError(error).message,
            });
          });
        }
        return { ok: true, platformFlow, downloading: true };
      } catch (error) {
        return {
          ok: false,
          reason: classifyFetchError(error).message,
          platformFlow,
        };
      }
    }
    // Fallback: browser.
    try {
      const release = await fetchLatestRelease({
        currentVersion: resolveAppVersion(app),
      });
      openReleasePage(release?.htmlUrl);
      return { ok: true, platformFlow };
    } catch (error) {
      openReleasePage(RELEASES_HTML_URL);
      return {
        ok: true,
        reason: classifyFetchError(error).message,
        platformFlow,
      };
    }
  });

  // In-app path: quit and install the downloaded update.
  // Never fires in unpackaged/dev builds.
  ipcMain.handle("onmyagent:updater:installAndRestart", async () => {
    if (!app.isPackaged || !autoUpdater) {
      // Dev / fallback: open the release page instead of pretending to install.
      openReleasePage(RELEASES_HTML_URL);
      return { ok: true, reason: "opened-release-page", platformFlow };
    }
    if (!downloadedUpdateInfo) {
      return {
        ok: false,
        reason: "Update has not finished downloading yet.",
        platformFlow,
      };
    }
    try {
      // isSilent=false (show installer UI on Windows), isForceRunAfter=true.
      autoUpdater.quitAndInstall(false, true);
      return { ok: true, platformFlow };
    } catch (error) {
      return {
        ok: false,
        reason: classifyFetchError(error).message,
        platformFlow,
      };
    }
  });

  let scheduledInitial = null;
  let intervalHandle = null;

  function scheduleAutoChecks() {
    if (scheduledInitial || intervalHandle) return;
    if (!app.isPackaged && UPDATE_CHECK_IN_DEV_DISABLED) {
      return;
    }
    scheduledInitial = setTimeout(() => {
      scheduledInitial = null;
      void performCheck({ silent: false });
    }, INITIAL_CHECK_DELAY_MS);
    intervalHandle = setInterval(() => {
      void performCheck({ silent: false });
    }, CHECK_INTERVAL_MS);
    if (typeof intervalHandle?.unref === "function") intervalHandle.unref();
    if (typeof scheduledInitial?.unref === "function") scheduledInitial.unref();
  }

  app.on("before-quit", () => {
    if (scheduledInitial) clearTimeout(scheduledInitial);
    if (intervalHandle) clearInterval(intervalHandle);
  });

  return {
    ensureAutoUpdater: async () => {
      const initialized = await initAutoUpdater();
      // If initialization failed on a platform that should support in-app
      // updates, fall back to the API checker (scheduleAutoChecks routes via
      // performCheck, which uses whatever is available).
      scheduleAutoChecks();
      return initialized;
    },
    checkForUpdatesNow: () => performCheck({ silent: false }),
  };
}
