import { t } from "@/i18n";

import { ALL_SKILLS } from "./skills-catalog";
import type { AgentRegistry } from "./agent-registry-types";

function localizedSkillCategoryLabel(category: string) {
  if (category === "built-in" || category === "内置技能") {
    return t("agents.skill_category_builtin");
  }
  if (category === "sourcing" || category === "货源与选品") {
    return t("agents.skill_category_sourcing");
  }
  if (category === "research" || category === "市场调研与分析") {
    return t("agents.skill_category_research");
  }
  return category;
}

function skillCategoryLabel(category: string) {
  return localizedSkillCategoryLabel(category);
}

const defaultRegistry: AgentRegistry = {
  version: 1,
  updatedAt: "2026-05-29T00:00:00.000Z",
  avatars: [
    {
      id: "pixel-business",
      style: "像素风",
      label: "业务专家",
      initials: "业",
      background: "#ffd9bf",
      foreground: "#6d3b1f",
      accent: "#c14d34",
    },
    {
      id: "pixel-tech",
      style: "像素风",
      label: "编程小能手",
      initials: "码",
      background: "#bfe5f7",
      foreground: "#16324f",
      accent: "#1f6fa5",
    },
    {
      id: "pixel-designer",
      style: "像素风",
      label: "设计专家",
      initials: "设",
      background: "#d6c4ff",
      foreground: "#4b2d7b",
      accent: "#9a6ce0",
    },
    {
      id: "pixel-product",
      style: "像素风",
      label: "产品专家",
      initials: "产",
      background: "#d8ddf0",
      foreground: "#4a4c63",
      accent: "#7c88b8",
    },
    {
      id: "pixel-retail",
      style: "像素风",
      label: "店铺运营",
      initials: "店",
      background: "#c8ebb3",
      foreground: "#355a18",
      accent: "#6aa33a",
    },
    {
      id: "adventurer-guide",
      style: "冒险家",
      label: "冒险家向导",
      initials: "向",
      background: "#f7d7c6",
      foreground: "#6d311d",
      accent: "#d77f47",
    },
    {
      id: "adventurer-scout",
      style: "冒险家",
      label: "市场斥候",
      initials: "市",
      background: "#d0f0dc",
      foreground: "#184c31",
      accent: "#4ca06d",
    },
    {
      id: "robot-analyst",
      style: "机器人",
      label: "分析机器人",
      initials: "分",
      background: "#e5e7f1",
      foreground: "#31374d",
      accent: "#7984af",
    },
    {
      id: "robot-helper",
      style: "机器人",
      label: "日常助手",
      initials: "助",
      background: "#d9eefc",
      foreground: "#174767",
      accent: "#4a94d2",
    },
    {
      id: "lorelei-mentor",
      style: "洛蕾莱",
      label: "灵感导师",
      initials: "灵",
      background: "#ffd7f0",
      foreground: "#70285f",
      accent: "#d468b3",
    },
    {
      id: "lorelei-operator",
      style: "洛蕾莱",
      label: t("agents.template_shopify_assistant_name"),
      initials: "商",
      background: "#e4f1cf",
      foreground: "#38531c",
      accent: "#88b84a",
    },
  ],
  templates: [
    {
      id: "blank-agent",
      name: "空白智能体",
      description: "从一个完全空白的画布开始。",
      quote: "我是一个专业的智能体助手，随时可以为你提供帮助。",
      tone: "专业",
      avatarStyle: "像素风",
      avatarOptionId: "pixel-tech",
      modelProvider: "自动",
      model: "Auto",
      enabledToolIds: ["filesystem", "web", "code", "utility"],
      skillIds: [],
      preferredName: "",
      preferredLanguage: "中文",
      userNote: "",
      userBackground: "",
      showInOverview: false,
      showInWizard: true,
    },
    {
      id: "daily-assistant",
      name: "日常助手",
      description: "适用于日常任务的通用助手，可用于写作、规划、总结和沟通。",
      quote: "我是一个高响应的日常助手，擅长把琐事变得清晰顺手。",
      tone: "友好",
      avatarStyle: "机器人",
      avatarOptionId: "robot-helper",
      modelProvider: "自动",
      model: "Auto",
      enabledToolIds: ["filesystem", "web", "utility", "memory"],
      skillIds: ["daily-summary", "meeting-followup"],
      preferredName: "",
      preferredLanguage: "中文",
      userNote: "",
      userBackground: "",
      showInOverview: true,
      showInWizard: true,
    },
    {
      id: "shopify-operator",
      name: "Shopify Operator",
      description: "策划丑萌毛绒玩具 Shopify 店铺，兼顾选品、页面和运营节奏。",
      quote: "我会陪你把店铺运营链路拆细，一步步把商品做起来。",
      tone: "专家",
      avatarStyle: "洛蕾莱",
      avatarOptionId: "lorelei-operator",
      modelProvider: "自动",
      model: "Auto",
      enabledToolIds: ["web", "commerce", "utility", "memory"],
      skillIds: ["product-trend-finder", "review-summary", "listing-optimizer"],
      preferredName: "",
      preferredLanguage: "中文",
      userNote: "",
      userBackground: "适合刚起步的 Shopify 店铺经营者。",
      showInOverview: false,
      showInWizard: true,
    },
    {
      id: "dropshipping-helper",
      name: "Dropshipping 助手",
      description:
        "覆盖完整代发流程的智能体，内置 Shopify 建店能力和商品分析能力。",
      quote: "我会帮你把代发流程拆成明确步骤，减少试错成本。",
      tone: "专业",
      avatarStyle: "冒险家",
      avatarOptionId: "adventurer-guide",
      modelProvider: "自动",
      model: "Auto",
      enabledToolIds: ["web", "commerce", "filesystem", "utility"],
      skillIds: ["supplier-shortlist", "listing-optimizer"],
      preferredName: "",
      preferredLanguage: "中文",
      userNote: "",
      userBackground: "",
      showInOverview: false,
      showInWizard: true,
    },
    {
      id: "engineering-helper",
      name: "编程专家",
      description:
        "你是一名专注于软件开发的专家，可用于写代码、调试、重构和代码评审。",
      quote: "我是一个编程小能手",
      tone: "友好",
      avatarStyle: "像素风",
      avatarOptionId: "pixel-tech",
      modelProvider: "自动",
      model: "Auto",
      enabledToolIds: ["filesystem", "code", "web", "memory", "collaboration"],
      skillIds: ["bug-triage", "refactor-checklist", "pr-brief"],
      preferredName: "",
      preferredLanguage: "中文",
      userNote: "",
      userBackground: "适合软件开发、调试、评审与自动化。",
      showInOverview: false,
      showInWizard: true,
    },
    {
      id: "commerce-expert",
      name: "电商专家",
      description: "电商运营、选品、供应链与增长顾问，擅长类目策略和经营分析。",
      quote: "我会从增长机会、风险和执行步骤三个角度帮你推进。",
      tone: "专家",
      avatarStyle: "像素风",
      avatarOptionId: "pixel-retail",
      modelProvider: "自动",
      model: "Auto",
      enabledToolIds: ["web", "commerce", "utility", "memory"],
      skillIds: ["product-trend-finder", "campaign-planner", "review-summary"],
      preferredName: "",
      preferredLanguage: "中文",
      userNote: "",
      userBackground: "",
      showInOverview: false,
      showInWizard: true,
    },
    {
      id: "finance-expert",
      name: "金融专家",
      description:
        "擅长股票与市场分析、财务建模、风险评估和情报研判的金融顾问。",
      quote: "我会帮你把市场信息压成判断框架，再给出更稳的行动建议。",
      tone: "专业",
      avatarStyle: "机器人",
      avatarOptionId: "robot-analyst",
      modelProvider: "自动",
      model: "Auto",
      enabledToolIds: ["web", "utility", "memory", "filesystem"],
      skillIds: ["product-trend-finder", "review-summary", "campaign-planner"],
      preferredName: "",
      preferredLanguage: "中文",
      userNote: "",
      userBackground: "适合投资研究、财务分析和市场追踪场景。",
      showInOverview: false,
      showInWizard: true,
    },
    {
      id: "product-manager",
      name: "产品经理",
      description:
        "产品规划与需求梳理伙伴，擅长 PRD、用户故事、优先级排序与方案对齐。",
      quote: "我会把需求说清楚、范围兜住，再帮你把优先级排明白。",
      tone: "专业",
      avatarStyle: "像素风",
      avatarOptionId: "pixel-product",
      modelProvider: "自动",
      model: "Auto",
      enabledToolIds: ["filesystem", "web", "memory", "utility"],
      skillIds: ["prd-outline", "meeting-followup", "copy-variants"],
      preferredName: "",
      preferredLanguage: "中文",
      userNote: "",
      userBackground: "适合产品规划、需求拆解和跨团队协作。",
      showInOverview: false,
      showInWizard: true,
    },
    {
      id: "tl",
      name: "TL",
      description:
        "你是一名资深的项目管理专家，负责整个人员协调、进度把控、风险识别，统筹项目各个阶段。",
      quote: "我会把复杂项目拆成清晰节奏，帮你盯住风险和关键节点。",
      tone: "专业",
      avatarStyle: "像素风",
      avatarOptionId: "pixel-retail",
      modelProvider: "自动",
      model: "Auto",
      enabledToolIds: ["filesystem", "web", "memory", "collaboration"],
      skillIds: ["project-radar", "meeting-followup"],
      preferredName: "",
      preferredLanguage: "中文",
      userNote: "",
      userBackground: "",
      showInOverview: false,
      showInWizard: false,
    },
    {
      id: "design-expert",
      name: "设计专家",
      description:
        "你是一名资深的设计专家，能够结合产品输入的 prd 文档和原型图生成高质量且符合用户交互习惯的稿件。",
      quote: "我会把需求转成结构清晰、交互顺手、可落地的设计方案。",
      tone: "创意",
      avatarStyle: "像素风",
      avatarOptionId: "pixel-designer",
      modelProvider: "自动",
      model: "Auto",
      enabledToolIds: ["filesystem", "web", "media", "utility"],
      skillIds: ["ux-critique", "copy-variants"],
      preferredName: "",
      preferredLanguage: "中文",
      userNote: "",
      userBackground: "",
      showInOverview: false,
      showInWizard: false,
    },
    {
      id: "product-expert",
      name: "产品专家",
      description:
        "你是一个资深的产品专家，擅长把业务方提出的述求转换成可逻辑自洽的产品方案，具备极高的产品造诣。",
      quote: "我会帮你把想法压成结构化方案，再补上边界和优先级。",
      tone: "专业",
      avatarStyle: "像素风",
      avatarOptionId: "pixel-product",
      modelProvider: "自动",
      model: "Auto",
      enabledToolIds: ["filesystem", "web", "memory", "utility"],
      skillIds: ["prd-outline", "meeting-followup"],
      preferredName: "",
      preferredLanguage: "中文",
      userNote: "",
      userBackground: "",
      showInOverview: false,
      showInWizard: false,
    },
    {
      id: "business-expert",
      name: "业务专家",
      description:
        "你是一名资深的业务专家，能够收集并分析市场数据，然后根据数据指标提出高质量的业务述求，述求清晰明确。",
      quote: "我会把市场机会和执行方案串起来，帮你判断什么值得做。",
      tone: "专家",
      avatarStyle: "像素风",
      avatarOptionId: "pixel-business",
      modelProvider: "自动",
      model: "Auto",
      enabledToolIds: ["web", "commerce", "memory", "utility"],
      skillIds: ["product-trend-finder", "campaign-planner"],
      preferredName: "",
      preferredLanguage: "中文",
      userNote: "",
      userBackground: "",
      showInOverview: false,
      showInWizard: false,
    },
  ],
  agents: [],
  skills: ALL_SKILLS.map((skill) => ({
    id: skill.id,
    category: skillCategoryLabel(skill.category),
    group: "",
    name: skill.name,
    description: skill.description,
    enabled: skill.enabled,
  })),
};


export function createDefaultAgentRegistry(): AgentRegistry {
  return structuredClone(defaultRegistry);
}
