export default {
  "session.batch_actions": "Batch actions",
  "session.batch_select_task": "Select {title}",
  "session.batch_select_section": "Select all tasks in {section}",
  "session.batch_select_all": "Select all",
  "session.batch_select_all_count": "Select all ({count})",
  "session.batch_cancel": "Cancel batch actions",
  "session.batch_archive_done": "Archived {count} tasks",
  "session.batch_delete_title": "Delete selected tasks?",
  "session.batch_delete_message":
    "This permanently deletes {count} selected tasks, their messages, and workspace files generated by those tasks. This cannot be undone.",
  "session.batch_delete_confirm": "Delete {count} tasks",
  "session.batch_delete_failed": "Some selected tasks could not be deleted",
} as const;
