// Ambient types for server-client-methods.mjs (literal inventory).
// Kept in sync with runtime groups in server-client-methods.mjs.

export type ServerClientMethodName =
  | "baseUrl"
  | "token"
  | "health"
  | "runtimeVersions"
  | "status"
  | "capabilities"
  | "getConfig"
  | "patchConfig"
  | "listReloadEvents"
  | "reloadEngine"
  | "listAudit"
  | "createVoiceRealtimeSession"
  | "listWorkspaces"
  | "createLocalWorkspace"
  | "updateWorkspaceDisplayName"
  | "activateWorkspace"
  | "deleteWorkspace"
  | "exportWorkspace"
  | "importWorkspace"
  | "previewWorkspaceImport"
  | "materializeBlueprintSessions"
  | "readOpencodeConfigFile"
  | "writeOpencodeConfigFile"
  | "readWorkspaceFile"
  | "statWorkspaceFile"
  | "writeWorkspaceFile"
  | "writeWorkspaceBinaryFile"
  | "downloadWorkspaceFile"
  | "listWorkspaceFiles"
  | "deleteSession"
  | "listSessions"
  | "getSession"
  | "getSessionMessages"
  | "getSessionSnapshot"
  | "listPlugins"
  | "addPlugin"
  | "removePlugin"
  | "listSkills"
  | "listHubSkills"
  | "installHubSkill"
  | "getSkill"
  | "upsertSkill"
  | "deleteSkill"
  | "getOpenCodeRouterHealth"
  | "getOpenCodeRouterTelegram"
  | "getOpenCodeRouterTelegramIdentities"
  | "getOpenCodeRouterSlackIdentities"
  | "sendOpenCodeRouterMessage"
  | "upsertOpenCodeRouterTelegramIdentity"
  | "deleteOpenCodeRouterTelegramIdentity"
  | "upsertOpenCodeRouterSlackIdentity"
  | "deleteOpenCodeRouterSlackIdentity"
  | "listMcp"
  | "addMcp"
  | "removeMcp"
  | "setMcpEnabled"
  | "logoutMcpAuth"
  | "listCommands"
  | "upsertCommand"
  | "deleteCommand"
  | "listAutomations"
  | "listAutomationRuns"
  | "createAutomation"
  | "updateAutomation"
  | "runAutomation"
  | "deleteAutomation"
  | "listSessionArchiveSessions"
  | "getSessionArchiveSession"
  | "openSessionArchiveEventsStream"
  | "openSessionArchiveSessionWatchStream"
  | "getSessionArchiveMessages"
  | "searchSessionArchiveSession"
  | "getSessionArchiveSessionUsage"
  | "renameSessionArchiveSession"
  | "trashSessionArchiveSession"
  | "restoreSessionArchiveSession"
  | "permanentlyDeleteSessionArchiveSession"
  | "listSessionArchiveTrash"
  | "emptySessionArchiveTrash"
  | "getSessionArchiveStarred"
  | "starSessionArchiveSession"
  | "unstarSessionArchiveSession"
  | "listSessionArchivePins"
  | "pinSessionArchiveMessage"
  | "unpinSessionArchiveMessage"
  | "openSessionArchiveSessionDirectory"
  | "resumeSessionArchiveSession"
  | "exportSessionArchiveSessionHtml"
  | "exportSessionArchiveSessionMarkdown"
  | "publishSessionArchiveSession"
  | "getSessionArchiveUsageSummary"
  | "getSessionArchiveUsageComparison"
  | "getSessionArchiveTopUsageSessions"
  | "getSessionArchiveAnalyticsBatch"
  | "getSessionArchiveAnalyticsSummary"
  | "getSessionArchiveAnalyticsActivity"
  | "getSessionArchiveAnalyticsHeatmap"
  | "getSessionArchiveAnalyticsProjects"
  | "getSessionArchiveAnalyticsHourOfWeek"
  | "getSessionArchiveAnalyticsSessions"
  | "getSessionArchiveAnalyticsVelocity"
  | "getSessionArchiveAnalyticsTools"
  | "getSessionArchiveAnalyticsSkills"
  | "getSessionArchiveAnalyticsTopSessions"
  | "getSessionArchiveAnalyticsSignals"
  | "getSessionArchiveAnalyticsSignalSessions"
  | "getSessionArchiveActivityReport"
  | "getSessionArchiveTrendTerms"
  | "listSessionArchiveInsights"
  | "generateSessionArchiveInsight"
  | "deleteSessionArchiveInsight"
  | "uploadSessionArchiveExport"
  | "importSessionArchiveClaudeAi"
  | "importSessionArchiveChatGpt"
  | "getSessionArchiveConfig"
  | "getSessionArchiveBackendsStatus"
  | "getSessionArchiveLifecycleStatus"
  | "updateSessionArchiveConfig"
  | "listSessionArchiveWorktreeMappings"
  | "upsertSessionArchiveWorktreeMapping"
  | "deleteSessionArchiveWorktreeMapping"
  | "applySessionArchiveWorktreeMappings"
  | "scanSessionArchiveSecrets"
  | "listSessionArchiveSecrets"
  | "searchSessionArchive"
  | "syncSessionArchive"
  | "getSessionArchiveSyncStatus"
  | "listArtifactPlugins"
  | "getArtifactPlugin"
  | "setArtifactPluginEnabled"
  | "setArtifactPluginSkillEnabled"
  | "getArtifactPluginConnection"
  | "uploadInbox"
  | "listInbox"
  | "downloadInboxItem"
  | "listArtifacts"
  | "resolveArtifacts"
  | "downloadArtifact"
  | "listUserEnvKeys"
  | "listUserEnv"
  | "upsertUserEnv"
  | "deleteUserEnv";

export declare const serverClientMethodGroups: {
  readonly system: readonly ServerClientMethodName[];
  readonly workspace: readonly ServerClientMethodName[];
  readonly sessions: readonly ServerClientMethodName[];
  readonly extensions: readonly ServerClientMethodName[];
  readonly sessionArchive: readonly ServerClientMethodName[];
  readonly artifactPlugins: readonly ServerClientMethodName[];
  readonly artifacts: readonly ServerClientMethodName[];
  readonly environment: readonly ServerClientMethodName[];
};

export declare const serverClientMethodNames: readonly ServerClientMethodName[];
