import type {
  ArtifactPluginManifest,
  ArtifactPluginRuntimeConfig,
} from "./artifact-plugin.js";

export type WorkspaceType = "local" | "remote";

export type RemoteType = "opencode" | "onmyagent";

export type ApprovalMode = "manual" | "auto";

export type TokenScope = "owner" | "collaborator" | "viewer";

export type SessionOriginKind = "assistant" | "expert" | "automation";

export type SessionOriginReadState = "ok" | "missing" | "corrupt" | "unknown_version";

export interface SessionOriginRecord {
  workspaceId: string;
  sessionId: string;
  kind: SessionOriginKind;
  agentId?: string;
  /** Marketplace/package identity. Required for new Expert writes. */
  packageName?: string;
  directory?: string;
  createdAt: number;
  updatedAt: number;
}

export interface SessionOriginTombstone {
  workspaceId: string;
  sessionId: string;
  agentId?: string;
  packageName?: string;
  deletedAt?: number;
  reason?: "user_delete" | "retention" | "migration" | string;
  /** Present on v2 mutations; absent on salvageable R0 fixtures. */
  revision?: number;
}

export interface SessionOriginListPayload {
  /** Public projection is always versioned even when the on-disk state is v1. */
  version: 2;
  revision: number;
  items: SessionOriginRecord[];
  tombstones: SessionOriginTombstone[];
  tombstoneWatermark?: number;
  /** False means a recoverable but non-authoritative state was read. */
  complete: boolean;
  state: SessionOriginReadState;
  /** The on-disk version, useful for migration diagnostics without paths. */
  sourceVersion?: number;
}

export type WorkspaceSessionScope = "directory" | "workspace";

export type WorkspaceSessionListFailureCode =
  | "inventory_unavailable"
  | "marker_invalid"
  | "directory_read_failed"
  | "directory_budget_exceeded";

/** Redacted source failure metadata; never contains an absolute filesystem path. */
export interface WorkspaceSessionListFailure {
  source: "workspace-root" | "expert-runtime";
  key: string;
  index: number;
  code: WorkspaceSessionListFailureCode;
}

/** Workspace-scope session list response; directory scope keeps the legacy shape. */
export interface WorkspaceSessionListPayload {
  scope: "workspace";
  items: unknown[];
  complete: boolean;
  failures: WorkspaceSessionListFailure[];
}

export interface SessionOriginUpsertPayload {
  kind: SessionOriginKind;
  agentId?: string;
  packageName?: string;
  directory?: string;
  expectedRevision?: number;
}

export interface SessionOriginDeleteResult {
  ok: true;
  revision: number;
  tombstone: SessionOriginTombstone;
}

/**
 * Redacted lifecycle diagnostics for Expert operations.
 *
 * These contracts deliberately contain counters, allow-listed enum values and
 * one-way hashes only. They are safe to expose from the diagnostics/status
 * surface; producers must never attach prompt/message/token/path payloads.
 */
export type ExpertLifecycleEventKind =
  | "directory_fetch"
  | "shadow_diff"
  | "heal"
  | "materialize"
  | "contract_assertion"
  | "delete"
  | "missing_skills";

export type ExpertLifecycleEventOutcome =
  | "started"
  | "succeeded"
  | "failed"
  | "partial"
  | "skipped";

export type ExpertLifecycleEventSource =
  | "workspace"
  | "cache"
  | "opencode"
  | "runtime"
  | "origin"
  | "marker";

export type ExpertLifecycleEventPhase =
  | "requested"
  | "fetch"
  | "compare"
  | "dry_run"
  | "apply"
  | "ensure"
  | "assert"
  | "forward"
  | "opencode"
  | "runtime"
  | "tombstone"
  | "complete";

export type ExpertLifecycleEventShadowChange =
  | "added"
  | "removed"
  | "changed"
  | "unchanged";

export type ExpertLifecycleEventHealAction =
  | "upgrade_marker"
  | "write_origin"
  | "restore_origin"
  | "skip";

export type ExpertLifecycleEventDeleteStep =
  | "request"
  | "opencode"
  | "runtime"
  | "tombstone"
  | "complete";

export interface ExpertLifecycleEventBase {
  /** Monotonic process-local sequence assigned by the ring. */
  sequence: number;
  /** Epoch milliseconds; generated by the ring when omitted by a producer. */
  timestamp: number;
  kind: ExpertLifecycleEventKind;
  outcome?: ExpertLifecycleEventOutcome;
  phase?: ExpertLifecycleEventPhase;
  source?: ExpertLifecycleEventSource;
  /** One-way hashes. Raw workspace/expert/session identifiers are never exported. */
  workspaceHash?: string;
  expertHash?: string;
  sessionHash?: string;
  code?: string;
  durationMs?: number;
  count?: number;
}

export interface ExpertLifecycleDirectoryFetchEvent extends ExpertLifecycleEventBase {
  kind: "directory_fetch";
  source?: ExpertLifecycleEventSource;
  complete?: boolean;
  failureCount?: number;
}

export interface ExpertLifecycleShadowDiffEvent extends ExpertLifecycleEventBase {
  kind: "shadow_diff";
  change: ExpertLifecycleEventShadowChange;
  changedFieldCount?: number;
}

export interface ExpertLifecycleHealEvent extends ExpertLifecycleEventBase {
  kind: "heal";
  action?: ExpertLifecycleEventHealAction;
  failureCount?: number;
}

export interface ExpertLifecycleMaterializeEvent extends ExpertLifecycleEventBase {
  kind: "materialize";
  declaredSkillCount?: number;
  installedSkillCount?: number;
  missingSkillCount?: number;
}

export interface ExpertLifecycleContractAssertionEvent extends ExpertLifecycleEventBase {
  kind: "contract_assertion";
  assertion?: "authorized_directory" | "marker" | "identity" | "agent" | "skills" | "plugin_isolation" | "prompt_budget";
}

export interface ExpertLifecycleDeleteEvent extends ExpertLifecycleEventBase {
  kind: "delete";
  step?: ExpertLifecycleEventDeleteStep;
  failureCount?: number;
}

export interface ExpertLifecycleMissingSkillsEvent extends ExpertLifecycleEventBase {
  kind: "missing_skills";
  declaredSkillCount?: number;
  missingSkillCount?: number;
}

export type ExpertLifecycleEvent =
  | ExpertLifecycleDirectoryFetchEvent
  | ExpertLifecycleShadowDiffEvent
  | ExpertLifecycleHealEvent
  | ExpertLifecycleMaterializeEvent
  | ExpertLifecycleContractAssertionEvent
  | ExpertLifecycleDeleteEvent
  | ExpertLifecycleMissingSkillsEvent;

/** Input accepted by the server event recorder; identifiers are hashed on write. */
export type ExpertLifecycleEventInput = {
  [K in ExpertLifecycleEventKind]: Omit<Extract<ExpertLifecycleEvent, { kind: K }>, "sequence" | "timestamp" | "workspaceHash" | "expertHash" | "sessionHash"> & {
    timestamp?: number;
    workspaceId?: string;
    expertId?: string;
    sessionId?: string;
    /** Existing redacted hashes may be forwarded without re-hashing. */
    workspaceHash?: string;
    expertHash?: string;
    sessionHash?: string;
  }
}[ExpertLifecycleEventKind];

export interface ExpertLifecycleEventSnapshot {
  schema: "onmyagent.expert-lifecycle-events";
  version: 1;
  capacity: 512;
  nextSequence: number;
  events: ExpertLifecycleEvent[];
}

export interface ExpertDirectoryShadowDiffRequest {
  change: ExpertLifecycleEventShadowChange;
  changedFieldCount?: number;
  count?: number;
}

export interface ExpertDirectoryShadowDiffResponse {
  ok: true;
  event: ExpertLifecycleShadowDiffEvent;
}

/** Typed identity/materialization contract used by Expert directory APIs. */
export interface ExpertDirectoryIdentity {
  agentId: string;
  packageName: string;
  sessionId: string;
  directory: string;
}

export interface ExpertDirectorySkills {
  declaredSkills: string[];
  installedSkills: string[];
  missingSkills: string[];
}

export interface ExpertDirectorySession extends ExpertDirectorySkills {
  sessionId: string;
  directory?: string;
  runtimeMissing: boolean;
  /** Unknown when OpenCode lookup was unavailable/incomplete. */
  sessionMissing?: boolean;
  tombstoned?: boolean;
}

export interface ExpertDirectoryRecord extends ExpertDirectorySkills {
  agentId: string;
  packageName: string;
  sessionIds: string[];
  runtimeDirectories: string[];
  sessions: ExpertDirectorySession[];
  runtimeMissing: boolean;
  sessionMissing?: boolean;
}

export type ExpertDirectoryFailureCode =
  | "origins_unavailable"
  | "inventory_unavailable"
  | "marker_invalid"
  | "marker_identity_conflict"
  | "legacy_identity_ambiguous"
  | "legacy_identity_unresolved"
  | "opencode_unavailable"
  | "session_lookup_failed"
  | "tombstone_protected"
  | "write_failed";

export interface ExpertDirectoryFailure {
  source: "origins" | "expert-runtime" | "opencode" | "heal";
  key: string;
  index: number;
  code: ExpertDirectoryFailureCode;
}

export interface ExpertDirectoryProjection {
  version: 1;
  schema: "onmyagent.expert-directory.v1";
  revision: number;
  complete: boolean;
  state: SessionOriginReadState | "session_lookup_failed";
  failures: ExpertDirectoryFailure[];
  inventoryFingerprint: string;
  records: ExpertDirectoryRecord[];
  tombstonedSessionIds: string[];
  lastComplete?: {
    revision: number;
    inventoryFingerprint: string;
  };
}

export interface ExpertDirectoryHealRequest {
  apply?: boolean;
  expectedRevision?: number;
  restoreTombstoned?: boolean;
}

export interface ExpertDirectoryHealAction {
  /** Omitted for unresolved legacy candidates; never populated with path keys. */
  sessionId?: string;
  agentId?: string;
  packageName?: string;
  directory?: string;
  kind: "upgrade_marker" | "write_origin" | "restore_origin" | "skip";
  result: "planned" | "applied" | "skipped" | "failed";
  code?: ExpertDirectoryFailureCode;
}

export interface ExpertDirectoryHealResponse {
  dryRun: boolean;
  complete: boolean;
  revision: number;
  projection: ExpertDirectoryProjection;
  actions: ExpertDirectoryHealAction[];
  failures: ExpertDirectoryFailure[];
}

/** Destructive Expert deletion is explicitly scoped to the user marketplace. */
export interface ExpertDeleteRequest {
  operationId: string;
  agentId: string;
  packageName: string;
  marketplace: "my-experts" | "experts";
  sessionIds?: string[];
  expectedRevision?: number;
}

export type ExpertDeleteStepState = "pending" | "completed" | "skipped" | "failed";

export interface ExpertDeleteStep {
  sessionId: string;
  openCode: ExpertDeleteStepState;
  runtime: ExpertDeleteStepState;
  tombstone: ExpertDeleteStepState;
  code?: string;
}

export interface ExpertDeleteResult {
  operationId: string;
  workspaceId: string;
  agentId: string;
  packageName: string;
  revision: number;
  state: "completed" | "partial" | "failed";
  steps: ExpertDeleteStep[];
}

export type SandboxBackend = "none" | "docker" | "container";

export type ProviderPlacement = "in-sandbox" | "host-machine" | "client-machine" | "external";

export type LogFormat = "pretty" | "json";

export interface WorkspaceConfig {
  id?: string;
  path: string;
  name?: string;
  preset?: string;
  workspaceType?: WorkspaceType;
  remoteType?: RemoteType;
  baseUrl?: string;
  directory?: string;
  displayName?: string;
  onmyagentHostUrl?: string;
  onmyagentToken?: string;
  onmyagentWorkspaceId?: string;
  onmyagentWorkspaceName?: string;
  sandboxBackend?: string;
  sandboxRunId?: string;
  sandboxContainerName?: string;
  opencodeUsername?: string;
  opencodePassword?: string;
}

export interface WorkspaceInfo {
  id: string;
  name: string;
  path: string;
  preset: string;
  workspaceType: WorkspaceType;
  remoteType?: RemoteType;
  baseUrl?: string;
  directory?: string;
  displayName?: string;
  onmyagentHostUrl?: string;
  onmyagentToken?: string;
  onmyagentWorkspaceId?: string;
  onmyagentWorkspaceName?: string;
  sandboxBackend?: string;
  sandboxRunId?: string;
  sandboxContainerName?: string;
  opencodeUsername?: string;
  opencodePassword?: string;
  opencode?: {
    baseUrl?: string;
    directory?: string;
    username?: string;
    password?: string;
  };
}

export interface OpencodeConfigFile {
  path: string;
  exists: boolean;
  content: string | null;
}

export interface ApprovalConfig {
  mode: ApprovalMode;
  timeoutMs: number;
}

export interface ServerConfig {
  host: string;
  port: number;
  token: string;
  hostToken: string;
  configPath?: string;
  opencodeBaseUrl?: string;
  opencodeDirectory?: string;
  opencodeUsername?: string;
  opencodePassword?: string;
  approval: ApprovalConfig;
  corsOrigins: string[];
  workspaces: WorkspaceInfo[];
  authorizedRoots: string[];
  readOnly: boolean;
  startedAt: number;
  tokenSource: "cli" | "env" | "file" | "generated";
  hostTokenSource: "cli" | "env" | "file" | "generated";
  logFormat: LogFormat;
  logRequests: boolean;
}

export interface Capabilities {
  schemaVersion: number;
  serverVersion: string;
  opencodeVersion: string;
  skills: { read: boolean; write: boolean; source: "onmyagent" | "opencode" };
  hub: {
    skills: {
      read: boolean;
      install: boolean;
      repo: { owner: string; name: string; ref: string };
    };
  };
  plugins: { read: boolean; write: boolean };
  mcp: { read: boolean; write: boolean };
  commands: { read: boolean; write: boolean };
  config: { read: boolean; write: boolean };
  /** Expert directory projection is shadow-only in the current renderer phase. */
  expertDirectory: { read: boolean; shadow: boolean };

  approvals: { mode: ApprovalMode; timeoutMs: number };
  sandbox: { enabled: boolean; backend: SandboxBackend };
  ui: { toy: boolean };
  tokens: { scoped: boolean; scopes: TokenScope[] };
  proxy: {
    opencode: boolean;
  };
  toolProviders: {
    browser: {
      enabled: boolean;
      placement: ProviderPlacement;
      mode: "none" | "headless" | "interactive";
    };
    files: {
      injection: boolean;
      outbox: boolean;
      inboxPath: string;
      outboxPath: string;
      maxBytes: number;
    };
  };
}

export type ReloadReason = "plugins" | "skills" | "mcp" | "config" | "agents" | "commands";

export type ReloadTrigger = {
  type: "skill" | "plugin" | "config" | "mcp" | "agent" | "command";
  name?: string;
  action?: "added" | "removed" | "updated";
  path?: string;
};

export interface ReloadEvent {
  id: string;
  seq: number;
  workspaceId: string;
  reason: ReloadReason;
  trigger?: ReloadTrigger;
  timestamp: number;
}

export interface ApiErrorBody {
  code: string;
  message: string;
  details?: unknown;
}

export interface PluginItem {
  spec: string;
  source: "config" | "dir.project" | "dir.global";
  scope: "project" | "global";
  path?: string;
}

export interface ArtifactPluginSkillItem {
  id: string;
  enabled: boolean;
  defaultEnabled: boolean;
}

export interface ArtifactPluginCatalogItem {
  id: string;
  manifest: ArtifactPluginManifest;
  runtime: ArtifactPluginRuntimeConfig;
  enabled: boolean;
  skills: ArtifactPluginSkillItem[];
}

export interface McpItem {
  name: string;
  config: Record<string, unknown>;
  source: "config.project" | "config.global" | "config.remote";
  disabledByTools?: boolean;
}

export interface SkillItem {
  name: string;
  path: string;
  description: string;
  scope: "project" | "global" | "built-in" | "onmyagent" | "local";
  trigger?: string;
  displayNameZh?: string;
  displayNameEn?: string;
  descriptionZh?: string;
  descriptionEn?: string;
}

export interface HubSkillItem {
  name: string;
  description: string;
  trigger?: string;
  source: {
    owner: string;
    repo: string;
    ref: string;
    path: string;
  };
}

export interface CommandItem {
  name: string;
  description?: string;
  template: string;
  agent?: string;
  model?: string | null;
  subtask?: boolean;
  scope: "workspace" | "global";
}

export type AutomationScene = "office";
export type AutomationFrequencyMode = "weekly" | "interval" | "once";
export type AutomationCycle = "daily" | "weekly" | "biweekly" | "monthly" | "yearly";
export type AutomationAccessMode = "default" | "full";
export type AutomationRunSource = "scheduled" | "manual";
export type AutomationRunStatus = "success" | "failed" | "skipped";

export interface AutomationModelRef {
  providerID: string;
  modelID: string;
}

export interface AutomationAgentSelection {
  id: string;
  name: string;
  description?: string;
  systemPrompt?: string;
  tools?: Record<string, boolean>;
  model?: AutomationModelRef;
}

export interface AutomationSchedule {
  mode: AutomationFrequencyMode;
  day: AutomationCycle;
  time: string;
  intervalMinutes?: number;
  weekdays?: number[];
  onceAt?: number;
  timezone?: string;
}

export interface AutomationEffectiveRange {
  startDate?: string;
  endDate?: string;
}

export interface AutomationRunSummary {
  status: AutomationRunStatus;
  source: AutomationRunSource;
  ranAt: number;
  sessionId?: string;
  groupName?: string;
  outputDirectory?: string;
  error?: string;
}

export interface AutomationRunLease {
  leaseId: string;
  startedAt: number;
  expiresAt: number;
  attempt: number;
  scheduledForAt: number;
  sessionId?: string;
  groupName?: string;
  outputDirectory?: string;
}

export interface AutomationTaskItem {
  id: string;
  scene: AutomationScene;
  title: string;
  prompt: string;
  sourceSessionId?: string;
  workspaceDirectory?: string;
  model?: AutomationModelRef;
  agent?: AutomationAgentSelection;
  accessMode?: AutomationAccessMode;
  schedule: AutomationSchedule;
  effectiveRange: AutomationEffectiveRange;
  enabled: boolean;
  createdAt: number;
  updatedAt: number;
  nextRunAt: number | null;
  running: AutomationRunLease | null;
  lastRun: AutomationRunSummary | null;
  runs: AutomationRunSummary[];
}

export interface AutomationTaskInput {
  scene: AutomationScene;
  title: string;
  prompt: string;
  sourceSessionId?: string | null;
  workspaceDirectory?: string | null;
  model?: AutomationModelRef | null;
  agent?: AutomationAgentSelection | null;
  accessMode?: AutomationAccessMode | null;
  schedule: AutomationSchedule;
  effectiveRange?: AutomationEffectiveRange;
  enabled?: boolean;
}

export interface AutomationRunHistoryResult {
  item: AutomationTaskItem;
  runs: AutomationRunSummary[];
  total: number;
}

export interface Actor {
  type: "remote" | "host";
  clientId?: string;
  tokenHash?: string;
  scope?: TokenScope;
}

export interface ApprovalRequest {
  id: string;
  workspaceId: string;
  action: string;
  summary: string;
  paths: string[];
  createdAt: number;
  actor: Actor;
}

export interface AuditEntry {
  id: string;
  workspaceId: string;
  actor: Actor;
  action: string;
  target: string;
  summary: string;
  timestamp: number;
}

export interface SkillContentResponse {
  item: SkillItem;
  content: string;
}

export interface WorkspaceFileContentResponse {
  path: string;
  content: string;
  bytes: number;
  updatedAt: number;
}

export interface WorkspaceFileWriteResponse {
  ok: boolean;
  path: string;
  bytes: number;
  updatedAt: number;
  revision?: string;
}

export interface WorkspaceExportResponse {
  workspaceId: string;
  exportedAt: number;
  opencode?: Record<string, unknown>;
  onmyagent?: Record<string, unknown>;
  skills?: Array<{ name: string; description?: string; trigger?: string; content: string }>;
  commands?: Array<{ name: string; description?: string; template?: string }>;
  files?: Array<{ path: string; content: string }>;
}

export interface WorkspaceImportChange {
  kind: "opencode" | "onmyagent" | "skill" | "command" | "file";
  action: "create" | "update" | "replace" | "delete" | "unchanged";
  label: string;
  path: string;
}

export interface WorkspaceImportPreviewResponse {
  fingerprint: string;
  summary: {
    total: number;
    create: number;
    update: number;
    replace: number;
    delete: number;
    unchanged: number;
  };
  changes: WorkspaceImportChange[];
}

export interface ArtifactItem {
  id: string;
  name?: string;
  path?: string;
  size?: number;
  createdAt?: number;
  updatedAt?: number;
  mime?: string;
}

export interface ArtifactListResponse {
  items: ArtifactItem[];
}

export interface ResolvedArtifactTarget {
  id: string;
  kind: "file" | "url";
  value: string;
  name: string;
  preview: "browser" | "markdown" | "sheet" | "image" | "pdf" | "html" | "text" | "external";
  confidence: number;
  reason: string;
  exists?: boolean;
  size?: number;
  updatedAt?: number;
  contentType?: string;
}

export interface WorkspaceFileStatResponse {
  ok: boolean;
  path: string;
  exists: boolean;
  kind?: "file" | "dir" | "other";
  size?: number;
  updatedAt?: number;
}

export interface WorkspaceFileCatalogEntry {
  path: string;
  kind: "file" | "dir";
  size: number;
  mtimeMs: number;
  revision: string;
}

export interface WorkspaceFileCatalogResponse {
  items: WorkspaceFileCatalogEntry[];
  total: number;
  truncated: boolean;
  generatedAt: number;
}

export interface InboxItem {
  id: string;
  name?: string;
  path?: string;
  size?: number;
  updatedAt?: number;
}

export interface InboxListResponse {
  items: InboxItem[];
}

export interface InboxUploadResponse {
  ok: boolean;
  path: string;
  bytes: number;
}

/** GET /health */
export interface ServerHealthResponse {
  ok: boolean;
  version: string;
  uptimeMs: number;
}

/** Renderer-facing capabilities slice (subset of Capabilities used by the HTTP client). */
export interface ServerClientCapabilities {
  skills: { read: boolean; write: boolean; source: "onmyagent" | "opencode" };
  hub?: {
    skills?: {
      read: boolean;
      install: boolean;
      repo?: { owner: string; name: string; ref: string };
    };
  };
  plugins: { read: boolean; write: boolean };
  mcp: { read: boolean; write: boolean };
  commands: { read: boolean; write: boolean };
  config: { read: boolean; write: boolean };
  expertDirectory?: { read: boolean; shadow: boolean };
  sandbox?: { enabled: boolean; backend: SandboxBackend };
  proxy?: { opencode: boolean };
  toolProviders?: {
    browser?: {
      enabled: boolean;
      placement: ProviderPlacement;
      mode: "none" | "headless" | "interactive";
    };
    files?: {
      injection: boolean;
      outbox: boolean;
      inboxPath: string;
      outboxPath: string;
      maxBytes: number;
    };
  };
}

/** GET /status diagnostics payload. */
export interface ServerStatusResponse {
  ok: boolean;
  version: string;
  uptimeMs: number;
  readOnly: boolean;
  approval: { mode: ApprovalMode; timeoutMs: number };
  corsOrigins: string[];
  workspaceCount: number;
  activeWorkspaceId?: string | null;
  selectedWorkspaceId?: string | null;
  workspace: WorkspaceInfo | null;
  authorizedRoots: string[];
  server: { host: string; port: number; configPath?: string | null };
  tokenSource: { client: string; host: string };
  /** Process-local redacted Expert lifecycle diagnostics (schema-versioned). */
  expertLifecycleEvents?: ExpertLifecycleEventSnapshot;
}

export type RuntimeServiceName = "onmyagent-server" | "opencode";

export interface RuntimeServiceSnapshot {
  name: RuntimeServiceName;
  enabled: boolean;
  running: boolean;
  targetVersion: string | null;
  actualVersion: string | null;
  upgradeAvailable: boolean;
}

/** GET /runtime/versions */
export interface RuntimeVersionsResponse {
  ok: boolean;
  orchestrator?: {
    version: string;
    startedAt: number;
  };
  worker?: {
    workspace: string;
    sandboxMode: string;
  };
  upgrade?: {
    status: "idle" | "running" | "failed";
    startedAt: number | null;
    finishedAt: number | null;
    error: string | null;
    operationId: string | null;
    services: RuntimeServiceName[];
  };
  services: RuntimeServiceSnapshot[];
}
