import { radixColors, tailwindSafelist } from './src/styles/tailwind-colors';
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
darkMode: 'class',
safelist: [
    tailwindSafelist
  ],
  theme: {
    borderRadius: {
      none: "0",
      inherit: "inherit",
      xs: "var(--dls-radius-xs)",
      sm: "var(--dls-radius-sm)",
      md: "var(--dls-radius-md)",
      lg: "var(--dls-radius-lg)",
      xl: "var(--dls-radius-xl)",
      full: "var(--dls-radius-pill)",
    },
    fontFamily: {
      sans: ["var(--dls-font-sans)"],
      heading: ["var(--dls-font-heading)"],
    },
    fontSize: {
      "2xs": ["var(--dls-text-2xs)", { lineHeight: "var(--dls-leading-normal)" }],
      xs: ["var(--dls-text-xs)", { lineHeight: "var(--dls-leading-normal)" }],
      sm: ["var(--dls-text-sm)", { lineHeight: "var(--dls-leading-normal)" }],
      base: ["var(--dls-text-base)", { lineHeight: "var(--dls-leading-normal)" }],
      lg: ["var(--dls-text-lg)", { lineHeight: "var(--dls-leading-tight)" }],
      xl: ["var(--dls-text-xl)", { lineHeight: "var(--dls-leading-tight)" }],
      "2xl": ["var(--dls-text-2xl)", { lineHeight: "var(--dls-leading-tight)" }],
      "3xl": ["var(--dls-text-3xl)", { lineHeight: "var(--dls-leading-tight)" }],
      "4xl": ["var(--dls-text-4xl)", { lineHeight: "var(--dls-leading-tight)" }],
      "5xl": ["var(--dls-text-5xl)", { lineHeight: "var(--dls-leading-tight)" }],
    },
    // OVERRIDE the base theme completely instead of extending it
    colors: {
      ...radixColors,
      dls: {
        surface: "var(--dls-surface)",
        background: "var(--dls-background)",
        canvas: "var(--dls-canvas)",
        "surface-muted": "var(--dls-surface-muted)",
        sidebar: "var(--dls-sidebar)",
        rail: "var(--dls-rail-bg)",
        "rail-active": "var(--dls-rail-active)",
        "rail-hover": "var(--dls-rail-hover)",
        "rail-border": "var(--dls-border)",
        border: "var(--dls-border)",
        "border-strong": "var(--dls-border-strong)",
        accent: "var(--dls-accent)",
        "accent-hover": "var(--dls-accent-hover)",
        signal: "var(--dls-signal)",
        text: "var(--dls-text-primary)",
        secondary: "var(--dls-text-secondary)",
        hover: "var(--dls-hover)",
        active: "var(--dls-active)",
        "list-selected": "var(--dls-list-selected)",
        decision: "var(--dls-decision-bg)",
        "decision-hover": "var(--dls-decision-hover)",
        "decision-soft": "var(--dls-decision-soft)",
        "icon-bg": "var(--dls-icon-bg)",
        "icon-fg": "var(--dls-icon-fg)",
        "icon-muted-bg": "var(--dls-icon-muted-bg)",
        "status-danger": "var(--dls-status-danger)",
        "status-danger-soft": "var(--dls-status-danger-soft)",
        "status-danger-fg": "var(--dls-status-danger-fg)",
        "status-warning": "var(--dls-status-warning)",
        "status-success-soft": "var(--dls-status-success-soft)",
        "status-success-fg": "var(--dls-status-success-fg)",
        "status-success-border": "var(--dls-status-success-border)",
        "brand-windows-red": "var(--dls-brand-windows-red)",
        "brand-windows-green": "var(--dls-brand-windows-green)",
        "brand-windows-blue": "var(--dls-brand-windows-blue)",
        "brand-windows-yellow": "var(--dls-brand-windows-yellow)",
        "brand-terminal": "var(--dls-brand-terminal)",
        "brand-orange": "var(--dls-brand-orange)",
        "brand-linkedin": "var(--dls-brand-linkedin)",
        "brand-gmail": "var(--dls-brand-gmail)",
        "brand-obsidian": "var(--dls-brand-obsidian)",
        "brand-notion": "var(--dls-brand-notion)",
        "brand-github": "var(--dls-brand-github)",
        "brand-drive": "var(--dls-brand-drive)",
        "brand-orange-soft": "var(--dls-brand-orange-soft)",
        "brand-orange-fg": "var(--dls-brand-orange-fg)",
        "chat-user-bg": "var(--dls-chat-user-bg)",
        "chat-agent-text": "var(--dls-chat-agent-text)",
        "shell-dark": "var(--dls-shell-dark)",
        online: "var(--dls-online)",
        "brand-vercel": "var(--dls-brand-vercel)",
        "brand-cloudflare": "var(--dls-brand-cloudflare)",
        "brand-replit-bg": "var(--dls-brand-replit-bg)",
        "brand-replit-fg": "var(--dls-brand-replit-fg)",
        "brand-web-soft": "var(--dls-brand-web-soft)",
        "brand-web-fg": "var(--dls-brand-web-fg)",
        "brand-google-text": "var(--dls-brand-google-text)",
        "brand-google-border": "var(--dls-brand-google-border)",
        "brand-subtle-text": "var(--dls-brand-subtle-text)",
        "brand-linear": "var(--dls-brand-linear)",
        "brand-zapier-soft": "var(--dls-brand-zapier-soft)",
        "brand-aws-soft": "var(--dls-brand-aws-soft)",
        "brand-aws-fg": "var(--dls-brand-aws-fg)",
        "brand-figma-yellow": "var(--dls-brand-figma-yellow)",
        "brand-figma-green": "var(--dls-brand-figma-green)",
        "brand-lovable-soft": "var(--dls-brand-lovable-soft)",
        "brand-lovable-fg": "var(--dls-brand-lovable-fg)",
        "brand-raycast": "var(--dls-brand-raycast)",
        "brand-coupang": "var(--dls-brand-coupang)",
        "brand-neutral-soft": "var(--dls-brand-neutral-soft)",
        "brand-faint-blue": "var(--dls-brand-faint-blue)",
        "icon-muted-fg": "var(--dls-icon-muted-fg)",
      },
      white: "#ffffff",
      black: "#000000",
    }
  }
};
