import type { SqliteDatabase } from "../core/sqlite.js";
import { createSessionArchiveAnalyticsApi } from "./session-archive-analytics.js";
import { createSessionArchiveConfigApi } from "./session-archive-config-api.js";
import { createSessionArchiveReadApi } from "./session-archive-read-api.js";
import { createSessionArchiveSearchApi } from "./session-archive-search-api.js";
import type { SessionArchiveStore } from "./session-archive-types.js";
import { createSessionArchiveUsageApi } from "./session-archive-usage.js";
import { createSessionArchiveWriteApi } from "./session-archive-write-api.js";

export type {
  SessionArchiveActivityReportInput,
  SessionArchiveContentSearchInput,
  SessionArchiveInsightFilterInput,
  SessionArchiveMessagesInput,
  SessionArchiveSearchInput,
  SessionArchiveSecretFindingsInput,
  SessionArchiveSessionListInput,
  SessionArchiveSessionSearchInput,
  SessionArchiveSkippedFileState,
  SessionArchiveSourceFileState,
  SessionArchiveStore,
  SessionArchiveTrashList,
  SessionArchiveTrendsTermsInput,
  SessionArchiveUsageComparisonInput,
  SessionArchiveUsageFilterInput,
  SessionArchiveUsageTopSessionsInput,
} from "./session-archive-types.js";

export function createSessionArchiveStore(
  dbPath: string,
  db: SqliteDatabase,
): SessionArchiveStore {
  const readApi = createSessionArchiveReadApi({ db, dbPath });
  const {
    listUsageEvents,
    getSourceFile,
    getSkippedFile,
    listSessions,
    sessionListWhere,
    getSession,
    getSessionIncludingDeleted,
    sessionExists,
    isSessionExcluded,
    listMessages,
    listAllMessages,
    listToolCalls,
    listChildren,
    getActivity,
    getTiming,
    listInsights,
    getInsight,
    listStarredSessions,
    listPins,
    listSessionPins,
    listTrash,
    getSessionDirectory,
    openSessionDirectory,
    resumeSession,
    exportSessionHtml,
    exportSessionMarkdown,
    publishSession,
    listSecretFindings,
    listWorktreeMappings,
  } = readApi;

  const usageApi = createSessionArchiveUsageApi({ db, getSession });
  const analyticsApi = createSessionArchiveAnalyticsApi({
    db,
    cacheScope: dbPath,
    listAllMessages,
    usageRows: usageApi.usageRows,
  });

  const writeApi = createSessionArchiveWriteApi({
    db,
    getSession,
    getSessionIncludingDeleted,
    sessionExists,
    isSessionExcluded,
    listAllMessages,
    getInsight,
    listWorktreeMappings,
    getActivityReport: analyticsApi.getActivityReport,
    getAnalyticsSummary: analyticsApi.getAnalyticsSummary,
    getAnalyticsTools: analyticsApi.getAnalyticsTools,
    getAnalyticsSignals: analyticsApi.getAnalyticsSignals,
  });

  const configApi = createSessionArchiveConfigApi({
    db,
    listWorktreeMappings,
  });
  const searchApi = createSessionArchiveSearchApi({
    db,
    sessionListWhere,
  });

  return {
    dbPath,
    close: () => db.close(),
    upsertSession: writeApi.upsertSession,
    replaceSessionMessages: writeApi.replaceSessionMessages,
    replaceSessionUsageEvents: writeApi.replaceSessionUsageEvents,
    listUsageEvents,
    getSourceFile,
    upsertSourceFile: writeApi.upsertSourceFile,
    getSkippedFile,
    upsertSkippedFile: writeApi.upsertSkippedFile,
    deleteSkippedFile: writeApi.deleteSkippedFile,
    listSessions,
    getSession,
    getSessionIncludingDeleted,
    isSessionExcluded,
    listMessages,
    listToolCalls,
    listChildren,
    getActivity,
    getTiming,
    getUsage: usageApi.getUsage,
    getUsageSummary: usageApi.getUsageSummary,
    getUsageComparison: usageApi.getUsageComparison,
    getTopUsageSessions: usageApi.getTopUsageSessions,
    getAnalyticsSummary: analyticsApi.getAnalyticsSummary,
    getAnalyticsActivity: analyticsApi.getAnalyticsActivity,
    getAnalyticsHeatmap: analyticsApi.getAnalyticsHeatmap,
    getAnalyticsProjects: analyticsApi.getAnalyticsProjects,
    getAnalyticsHourOfWeek: analyticsApi.getAnalyticsHourOfWeek,
    getAnalyticsSessionShape: analyticsApi.getAnalyticsSessionShape,
    getAnalyticsVelocity: analyticsApi.getAnalyticsVelocity,
    getAnalyticsTools: analyticsApi.getAnalyticsTools,
    getAnalyticsSkills: analyticsApi.getAnalyticsSkills,
    getAnalyticsTopSessions: analyticsApi.getAnalyticsTopSessions,
    getAnalyticsSignals: analyticsApi.getAnalyticsSignals,
    getAnalyticsSignalSessions: analyticsApi.getAnalyticsSignalSessions,
    getAnalyticsBatch: analyticsApi.getAnalyticsBatch,
    getActivityReport: analyticsApi.getActivityReport,
    getTrendsTerms: analyticsApi.getTrendsTerms,
    listInsights,
    getInsight,
    deleteInsight: writeApi.deleteInsight,
    generateInsight: writeApi.generateInsight,
    starSession: writeApi.starSession,
    unstarSession: writeApi.unstarSession,
    listStarredSessions,
    bulkStarSessions: writeApi.bulkStarSessions,
    pinMessage: writeApi.pinMessage,
    unpinMessage: writeApi.unpinMessage,
    listPins,
    listSessionPins,
    renameSession: writeApi.renameSession,
    trashSession: writeApi.trashSession,
    restoreSession: writeApi.restoreSession,
    permanentlyDeleteSession: writeApi.permanentlyDeleteSession,
    listTrash,
    emptyTrash: writeApi.emptyTrash,
    getSessionDirectory,
    openSessionDirectory,
    resumeSession,
    exportSessionHtml,
    exportSessionMarkdown,
    publishSession,
    importUploadedExport: writeApi.importUploadedExport,
    importClaudeAiExport: writeApi.importClaudeAiExport,
    importChatGptExport: writeApi.importChatGptExport,
    getConfigSnapshot: configApi.getConfigSnapshot,
    updateConfig: configApi.updateConfig,
    getBackendsStatus: configApi.getBackendsStatus,
    upsertWorktreeMapping: writeApi.upsertWorktreeMapping,
    deleteWorktreeMapping: writeApi.deleteWorktreeMapping,
    applyWorktreeMappings: writeApi.applyWorktreeMappings,
    scanSecrets: writeApi.scanSecrets,
    listSecretFindings,
    searchSession: searchApi.searchSession,
    searchContent: searchApi.searchContent,
    search: searchApi.search,
    stats: searchApi.stats,
  };
}
