export function opencodeBrowserNodeReplToolSource(): string {
  return [
    'import { randomUUID } from "node:crypto"',
    'import net from "node:net"',
    'import { tool } from "@opencode-ai/plugin"',
    "",
    "const encode = (value) => {",
    "  const payload = Buffer.from(JSON.stringify(value), 'utf8')",
    "  const frame = Buffer.allocUnsafe(payload.length + 4)",
    "  frame.writeUInt32LE(payload.length, 0)",
    "  payload.copy(frame, 4)",
    "  return frame",
    "}",
    "",
    "const connect = (endpoint) => new Promise((resolve, reject) => {",
    "  const socket = net.createConnection(endpoint)",
    "  socket.once('connect', () => resolve(socket))",
    "  socket.once('error', reject)",
    "})",
    "",
    "const createRpc = (socket) => {",
    "  let buffer = Buffer.alloc(0)",
    "  let nextId = 0",
    "  const pending = new Map()",
    "  socket.on('data', (chunk) => {",
    "    buffer = Buffer.concat([buffer, chunk])",
    "    while (buffer.length >= 4) {",
    "      const length = buffer.readUInt32LE(0)",
    "      if (buffer.length < length + 4) return",
    "      const message = JSON.parse(buffer.subarray(4, length + 4).toString('utf8'))",
    "      buffer = buffer.subarray(length + 4)",
    "      const waiter = pending.get(message.id)",
    "      if (!waiter) continue",
    "      pending.delete(message.id)",
    "      if (message.error) waiter.reject(new Error(message.error.message))",
    "      else waiter.resolve(message.result)",
    "    }",
    "  })",
    "  socket.on('error', (error) => {",
    "    for (const waiter of pending.values()) waiter.reject(error)",
    "    pending.clear()",
    "  })",
    "  return (request) => new Promise((resolve, reject) => {",
    "    nextId += 1",
    "    pending.set(nextId, { resolve, reject })",
    "    socket.write(encode({ jsonrpc: '2.0', id: nextId, ...request }))",
    "  })",
    "}",
    "",
    "export default tool({",
    '  description: "ONLY supported way to control OnMyAgent\'s built-in in-app browser (right-side Browser panel). Do NOT use shell, CDP, remote-debugging-port, 9823, 9222, Playwright-against-Chrome, or external browser tools. Open/navigate with: globalThis.browser ??= await agent.browsers.getDefault(); globalThis.tab ??= await browser.tabs.new({ url }); return plain JSON ({ id, url, title }). Keep Browser/Tab handles in variables across calls. State persists for this session.",',
    "  args: {",
    '    code: tool.schema.string().describe("JavaScript for the browser REPL. Multi-statement blocks with return are supported. Example open: globalThis.browser ??= await agent.browsers.getDefault(); globalThis.tab ??= await browser.tabs.new({ url: \\"https://example.com\\" }); return { id: tab.id, url: await tab.url() }"),',
    "  },",
    "  async execute(args, context) {",
    "    const endpoint = String(process.env.ONMYAGENT_BROWSER_RPC_ENDPOINT || '').trim()",
    "    const bootstrap = String(process.env.ONMYAGENT_BROWSER_RPC_BOOTSTRAP || '').trim()",
    "    if (!endpoint || !bootstrap) {",
    "      throw new Error(",
    "        'OnMyAgent Browser runtime is unavailable (RPC not injected). ' +",
    "          'Retry in the desktop app with browser-automation enabled. ' +",
    "          'Do NOT fall back to CDP ports (9823/9222), remote-debugging-port, or external Chrome — those are not the in-app browser.'",
    "      )",
    "    }",
    "    const sessionId = String(context.sessionID || '').trim()",
    "    if (!sessionId) throw new Error('OpenCode did not provide a Browser session identity')",
    "    const messageId = String(context.messageID || randomUUID())",
    "    const requestContext = {",
    "      workspaceId: String(context.directory || 'workspace'),",
    "      sessionId,",
    "      messageId,",
    "      turnId: messageId,",
    "      agentId: String(context.agent || 'opencode'),",
    "      backend: 'in-app',",
    "    }",
    "    const socket = await connect(endpoint)",
    "    const rpc = createRpc(socket)",
    "    try {",
    "      const issued = await rpc({ method: \"getCapability\", params: { bootstrap, peerPid: process.pid }, context: requestContext })",
    "      const result = await rpc({ method: \"nodeReplWrite\", params: { code: args.code }, context: requestContext, capability: issued.capability })",
    "      // Prefer the evaluated value so the model does not dig through { value: ... } wrappers.",
    "      const payload = result && typeof result === 'object' && 'value' in result ? result.value : result",
    "      return typeof payload === 'string' ? payload : JSON.stringify(payload, null, 2)",
    "    } finally {",
    "      socket.end()",
    "    }",
    "  },",
    "})",
    "",
  ].join("\n");
}
