export function printHelp(): void {
  const message = [
    "onmyagent",
    "",
    "Usage:",
    "  onmyagent start [--workspace <path>] [options]",
    "  onmyagent serve [--workspace <path>] [options]",
    "  onmyagent daemon [run|start|stop|status] [options]",
    "  onmyagent workspace <action> [options]",
    "  onmyagent instance dispose <id> [options]",
    "  onmyagent approvals list --onmyagent-url <url> --host-token <token>",
    "  onmyagent approvals reply <id> --allow|--deny --onmyagent-url <url> --host-token <token>",
    "  onmyagent files <action> [options]",
    "  onmyagent status [--onmyagent-url <url>] [--opencode-url <url>]",
    "",
    "Commands:",
    "  start                   Start OpenCode + OnMyAgent server + OpenCodeRouter",
    "  serve                   Start services and stream logs (no TUI)",
    "  daemon                  Run orchestrator router daemon (multi-workspace)",
    "  workspace               Manage workspaces (add/list/switch/path)",
    "  instance                Manage workspace instances (dispose)",
    "  approvals list           List pending approval requests",
    "  approvals reply <id>     Approve or deny a request",
    "  files                   Manage file sessions and batch file sync",
    "  status                  Check OpenCode/OnMyAgent health",
    "",
    "Options:",
    "  --workspace <path>        Workspace directory (default: cwd)",
    "  --data-dir <path>         Data dir for orchestrator router state",
    "  --daemon-host <host>      Host for orchestrator router daemon (default: 127.0.0.1)",
    "  --daemon-port <port>      Port for orchestrator router daemon (default: random)",
    "  --opencode-bin <path>     Path to opencode binary (requires --allow-external)",
    "  --opencode-host <host>    Bind host for opencode serve (loopback only, default: 127.0.0.1)",
    "  --opencode-port <port>    Port for opencode serve (default: random)",
    "  --opencode-workdir <p>    Workdir for router-managed opencode serve",
    "  --opencode-log-level <l>  Log level for opencode serve (DEBUG, INFO, WARN, ERROR; default: opencode default)",
    "  --opencode-auth           OpenCode basic auth is always enabled",
    "  --opencode-hot-reload     Enable OpenCode hot reload (default: true)",
    "  --opencode-hot-reload-debounce-ms <ms>  Debounce window for hot reload triggers (default: 700)",
    "  --opencode-hot-reload-cooldown-ms <ms>  Minimum interval between hot reloads (default: 1500)",
    "  --opencode-username <u>   Internal-only override for managed OpenCode auth username",
    "  --opencode-password <p>   Internal-only override for managed OpenCode auth password",
    "  --onmyagent-host <host>    Bind host for onmyagent-server (default: 127.0.0.1)",
    "  --onmyagent-port <port>    Port for onmyagent-server (default: 8787)",
    "  --remote-access           Expose OnMyAgent on 0.0.0.0 for remote sharing",
    "  --onmyagent-token <token>  Client token for onmyagent-server",
    "  --onmyagent-host-token <t> Host token for approvals",
    "  --workspace-id <id>       Workspace id for file session commands",
    "  --session-id <id>         File session id for file session commands",
    "  --path <path>             Workspace-relative file path",
    "  --paths <list>            Comma-separated list of workspace-relative file paths",
    "  --ttl-seconds <n>         File session TTL in seconds",
    "  --content <text>          Inline content for file writes",
    "  --content-base64 <b64>    Base64 content for file writes",
    "  --file <path>             Local file path for file writes",
    "  --if-match <revision>     Revision precondition for file writes",
    "  --from <path>             Source path for rename",
    "  --to <path>               Destination path for rename",
    "  --write                   Request writable file session",
    "  --force                   Force write despite revision mismatch",
    "  --recursive               Recursive delete for files delete",
    "  --approval <mode>         manual | auto (default: manual)",
    "  --approval-timeout <ms>   Approval timeout in ms",
    "  --read-only               Start OnMyAgent server in read-only mode",
    "  --cors <origins>          Comma-separated CORS origins or *",
    "  --connect-host <host>     Override LAN host used for pairing URLs",
    "  --onmyagent-server-bin <p> Path to onmyagent-server binary (requires --allow-external)",
    "  --opencode-router-bin <path>     Path to opencodeRouter binary (requires --allow-external)",
    "  --opencode-router-health-port <p> Health server port for opencodeRouter (default: random)",
    "  --opencode-router                Enable opencodeRouter sidecar (default from workspace messaging config)",
    "  --no-opencode-router             Disable opencodeRouter sidecar",
    "  --opencode-router-required       Exit if opencodeRouter stops",
    "  --allow-external          Allow external sidecar binaries (dev only, required for custom bins)",
    "  --sidecar-dir <path>      Cache directory for downloaded sidecars",
    "  --sidecar-base-url <url>  Base URL for sidecar downloads",
    "  --sidecar-manifest <url>  Override sidecar manifest URL",
    "  --sidecar-source <mode>   auto | bundled | downloaded | external",
    "  --opencode-source <mode>  auto | bundled | downloaded | external",
    "  --check                   Run health checks then exit",
    "  --check-events            Verify SSE events during check",
    "  --tui                     Force interactive dashboard (TTY only)",
    "  --no-tui                  Disable interactive dashboard",
    "  --detach                  Detach after start and keep services running",
    "  --sandbox <mode>          none | auto | docker | container (default: none)",
    "  --sandbox-image <ref>     Container image for sandbox mode",
    "  --sandbox-persist-dir <p> Persist dir mounted into sandbox (default: per-workspace)",
    "  --sandbox-mount <specs>   Extra mounts (validated): hostPath:subpath[:ro|rw] (requires allowlist)",
    "  --json                    Output JSON when applicable",
    "  --verbose                 Print additional diagnostics",
    "  --log-format <format>     Log output format: pretty | json",
    "  --color                   Force ANSI color output",
    "  --no-color                Disable ANSI color output",
    "  --run-id <id>             Correlation id for logs (default: random UUID)",
    "  --help                    Show help",
    "  --version                 Show version",
  ].join("\n");
  console.log(message);
}
